// Prayer-times directory dataset: countries and cities with coordinates,
// IANA timezones and default calculation methods. Names in ar / en / ur.
import type { MethodId } from './prayer';

export interface PtCountry { slug: string; code: string; ar: string; en: string; ur: string; method: MethodId }
export interface PtCity { slug: string; cc: string; ar: string; en: string; ur: string; lat: number; lng: number; zone: string; method?: MethodId }

export const PT_COUNTRIES: PtCountry[] = [
  { slug: 'saudi-arabia',         code: 'sa', ar: 'السعودية',              en: 'Saudi Arabia',         ur: 'سعودی عرب',          method: 'Makkah' },
  { slug: 'egypt',                code: 'eg', ar: 'مصر',                   en: 'Egypt',                ur: 'مصر',                method: 'Egypt' },
  { slug: 'united-arab-emirates', code: 'ae', ar: 'الإمارات',              en: 'United Arab Emirates', ur: 'متحدہ عرب امارات',   method: 'Gulf' },
  { slug: 'kuwait',               code: 'kw', ar: 'الكويت',                en: 'Kuwait',               ur: 'کویت',               method: 'Kuwait' },
  { slug: 'qatar',                code: 'qa', ar: 'قطر',                   en: 'Qatar',                ur: 'قطر',                method: 'Qatar' },
  { slug: 'bahrain',              code: 'bh', ar: 'البحرين',               en: 'Bahrain',              ur: 'بحرین',              method: 'Gulf' },
  { slug: 'oman',                 code: 'om', ar: 'عُمان',                 en: 'Oman',                 ur: 'عمان',               method: 'Gulf' },
  { slug: 'jordan',               code: 'jo', ar: 'الأردن',                en: 'Jordan',               ur: 'اردن',               method: 'MWL' },
  { slug: 'palestine',            code: 'ps', ar: 'فلسطين',                en: 'Palestine',            ur: 'فلسطین',             method: 'MWL' },
  { slug: 'lebanon',              code: 'lb', ar: 'لبنان',                 en: 'Lebanon',              ur: 'لبنان',              method: 'MWL' },
  { slug: 'syria',                code: 'sy', ar: 'سوريا',                 en: 'Syria',                ur: 'شام',                method: 'MWL' },
  { slug: 'iraq',                 code: 'iq', ar: 'العراق',                en: 'Iraq',                 ur: 'عراق',               method: 'MWL' },
  { slug: 'yemen',                code: 'ye', ar: 'اليمن',                 en: 'Yemen',                ur: 'یمن',                method: 'Makkah' },
  { slug: 'turkey',               code: 'tr', ar: 'تركيا',                 en: 'Turkey',               ur: 'ترکی',               method: 'Turkey' },
  { slug: 'iran',                 code: 'ir', ar: 'إيران',                 en: 'Iran',                 ur: 'ایران',              method: 'Tehran' },
  { slug: 'pakistan',             code: 'pk', ar: 'باكستان',               en: 'Pakistan',             ur: 'پاکستان',            method: 'Karachi' },
  { slug: 'india',                code: 'in', ar: 'الهند',                 en: 'India',                ur: 'بھارت',              method: 'Karachi' },
  { slug: 'bangladesh',           code: 'bd', ar: 'بنغلاديش',              en: 'Bangladesh',           ur: 'بنگلہ دیش',          method: 'Karachi' },
  { slug: 'afghanistan',          code: 'af', ar: 'أفغانستان',             en: 'Afghanistan',          ur: 'افغانستان',          method: 'Karachi' },
  { slug: 'indonesia',            code: 'id', ar: 'إندونيسيا',             en: 'Indonesia',            ur: 'انڈونیشیا',          method: 'Singapore' },
  { slug: 'malaysia',             code: 'my', ar: 'ماليزيا',               en: 'Malaysia',             ur: 'ملائیشیا',           method: 'Singapore' },
  { slug: 'singapore',            code: 'sg', ar: 'سنغافورة',              en: 'Singapore',            ur: 'سنگاپور',            method: 'Singapore' },
  { slug: 'brunei',               code: 'bn', ar: 'بروناي',                en: 'Brunei',               ur: 'برونائی',            method: 'Singapore' },
  { slug: 'morocco',              code: 'ma', ar: 'المغرب',                en: 'Morocco',              ur: 'مراکش',              method: 'MWL' },
  { slug: 'algeria',              code: 'dz', ar: 'الجزائر',               en: 'Algeria',              ur: 'الجزائر',            method: 'MWL' },
  { slug: 'tunisia',              code: 'tn', ar: 'تونس',                  en: 'Tunisia',              ur: 'تیونس',              method: 'MWL' },
  { slug: 'libya',                code: 'ly', ar: 'ليبيا',                 en: 'Libya',                ur: 'لیبیا',              method: 'MWL' },
  { slug: 'sudan',                code: 'sd', ar: 'السودان',               en: 'Sudan',                ur: 'سوڈان',              method: 'Makkah' },
  { slug: 'somalia',              code: 'so', ar: 'الصومال',               en: 'Somalia',              ur: 'صومالیہ',            method: 'MWL' },
  { slug: 'nigeria',              code: 'ng', ar: 'نيجيريا',               en: 'Nigeria',              ur: 'نائیجیریا',          method: 'MWL' },
  { slug: 'senegal',              code: 'sn', ar: 'السنغال',               en: 'Senegal',              ur: 'سینیگال',            method: 'MWL' },
  { slug: 'ethiopia',             code: 'et', ar: 'إثيوبيا',               en: 'Ethiopia',             ur: 'ایتھوپیا',           method: 'MWL' },
  { slug: 'kenya',                code: 'ke', ar: 'كينيا',                 en: 'Kenya',                ur: 'کینیا',              method: 'MWL' },
  { slug: 'south-africa',         code: 'za', ar: 'جنوب أفريقيا',          en: 'South Africa',         ur: 'جنوبی افریقہ',       method: 'MWL' },
  { slug: 'united-kingdom',       code: 'gb', ar: 'المملكة المتحدة',       en: 'United Kingdom',       ur: 'برطانیہ',            method: 'MWL' },
  { slug: 'france',               code: 'fr', ar: 'فرنسا',                 en: 'France',               ur: 'فرانس',              method: 'MWL' },
  { slug: 'germany',              code: 'de', ar: 'ألمانيا',               en: 'Germany',              ur: 'جرمنی',              method: 'MWL' },
  { slug: 'netherlands',          code: 'nl', ar: 'هولندا',                en: 'Netherlands',          ur: 'نیدرلینڈز',          method: 'MWL' },
  { slug: 'belgium',              code: 'be', ar: 'بلجيكا',                en: 'Belgium',              ur: 'بیلجیم',             method: 'MWL' },
  { slug: 'spain',                code: 'es', ar: 'إسبانيا',               en: 'Spain',                ur: 'اسپین',              method: 'MWL' },
  { slug: 'italy',                code: 'it', ar: 'إيطاليا',               en: 'Italy',                ur: 'اٹلی',               method: 'MWL' },
  { slug: 'sweden',               code: 'se', ar: 'السويد',                en: 'Sweden',               ur: 'سویڈن',              method: 'MWL' },
  { slug: 'norway',               code: 'no', ar: 'النرويج',               en: 'Norway',               ur: 'ناروے',              method: 'MWL' },
  { slug: 'denmark',              code: 'dk', ar: 'الدانمارك',             en: 'Denmark',              ur: 'ڈنمارک',             method: 'MWL' },
  { slug: 'austria',              code: 'at', ar: 'النمسا',                en: 'Austria',              ur: 'آسٹریا',             method: 'MWL' },
  { slug: 'switzerland',          code: 'ch', ar: 'سويسرا',                en: 'Switzerland',          ur: 'سوئٹزرلینڈ',         method: 'MWL' },
  { slug: 'russia',               code: 'ru', ar: 'روسيا',                 en: 'Russia',               ur: 'روس',                method: 'MWL' },
  { slug: 'united-states',        code: 'us', ar: 'الولايات المتحدة',      en: 'United States',        ur: 'امریکہ',             method: 'ISNA' },
  { slug: 'canada',               code: 'ca', ar: 'كندا',                  en: 'Canada',               ur: 'کینیڈا',             method: 'ISNA' },
  { slug: 'australia',            code: 'au', ar: 'أستراليا',              en: 'Australia',            ur: 'آسٹریلیا',           method: 'MWL' },
  { slug: 'azerbaijan',           code: 'az', ar: 'أذربيجان',              en: 'Azerbaijan',           ur: 'آذربائیجان',         method: 'MWL' },
  { slug: 'uzbekistan',           code: 'uz', ar: 'أوزبكستان',             en: 'Uzbekistan',           ur: 'ازبکستان',           method: 'Karachi' },
  { slug: 'kazakhstan',           code: 'kz', ar: 'كازاخستان',             en: 'Kazakhstan',           ur: 'قازقستان',           method: 'Karachi' },
  { slug: 'bosnia',               code: 'ba', ar: 'البوسنة والهرسك',       en: 'Bosnia & Herzegovina', ur: 'بوسنیا',             method: 'MWL' },
  { slug: 'albania',              code: 'al', ar: 'ألبانيا',               en: 'Albania',              ur: 'البانیہ',            method: 'MWL' },
  { slug: 'kosovo',               code: 'xk', ar: 'كوسوفو',                en: 'Kosovo',               ur: 'کوسوو',              method: 'MWL' },
  { slug: 'north-macedonia',      code: 'mk', ar: 'مقدونيا الشمالية',      en: 'North Macedonia',      ur: 'شمالی مقدونیہ',      method: 'MWL' },
  { slug: 'maldives',             code: 'mv', ar: 'المالديف',              en: 'Maldives',             ur: 'مالدیپ',             method: 'Karachi' },
  { slug: 'sri-lanka',            code: 'lk', ar: 'سريلانكا',              en: 'Sri Lanka',            ur: 'سری لنکا',           method: 'Karachi' },
  { slug: 'china',                code: 'cn', ar: 'الصين',                 en: 'China',                ur: 'چین',                method: 'MWL' },
  { slug: 'philippines',          code: 'ph', ar: 'الفلبين',               en: 'Philippines',          ur: 'فلپائن',             method: 'Singapore' },
  { slug: 'thailand',             code: 'th', ar: 'تايلاند',               en: 'Thailand',             ur: 'تھائی لینڈ',         method: 'Singapore' },
  { slug: 'japan',                code: 'jp', ar: 'اليابان',               en: 'Japan',                ur: 'جاپان',              method: 'MWL' },
];

export const PT_CITIES: PtCity[] = [
  // Saudi Arabia
  { slug: 'makkah',   cc: 'sa', ar: 'مكة المكرمة',     en: 'Makkah',   ur: 'مکہ مکرمہ',  lat: 21.4225, lng: 39.8262, zone: 'Asia/Riyadh' },
  { slug: 'madinah',  cc: 'sa', ar: 'المدينة المنورة', en: 'Madinah',  ur: 'مدینہ منورہ', lat: 24.4686, lng: 39.6142, zone: 'Asia/Riyadh' },
  { slug: 'riyadh',   cc: 'sa', ar: 'الرياض',          en: 'Riyadh',   ur: 'ریاض',       lat: 24.7136, lng: 46.6753, zone: 'Asia/Riyadh' },
  { slug: 'jeddah',   cc: 'sa', ar: 'جدة',             en: 'Jeddah',   ur: 'جدہ',        lat: 21.4858, lng: 39.1925, zone: 'Asia/Riyadh' },
  { slug: 'dammam',   cc: 'sa', ar: 'الدمام',          en: 'Dammam',   ur: 'دمام',       lat: 26.4207, lng: 50.0888, zone: 'Asia/Riyadh' },
  { slug: 'taif',     cc: 'sa', ar: 'الطائف',          en: 'Taif',     ur: 'طائف',       lat: 21.2703, lng: 40.4158, zone: 'Asia/Riyadh' },
  { slug: 'tabuk',    cc: 'sa', ar: 'تبوك',            en: 'Tabuk',    ur: 'تبوک',       lat: 28.3838, lng: 36.5550, zone: 'Asia/Riyadh' },
  { slug: 'abha',     cc: 'sa', ar: 'أبها',            en: 'Abha',     ur: 'ابہا',       lat: 18.2164, lng: 42.5053, zone: 'Asia/Riyadh' },
  { slug: 'buraidah', cc: 'sa', ar: 'بريدة',           en: 'Buraidah', ur: 'بریدہ',      lat: 26.3260, lng: 43.9750, zone: 'Asia/Riyadh' },
  { slug: 'khobar',   cc: 'sa', ar: 'الخبر',           en: 'Khobar',   ur: 'الخبر',      lat: 26.2172, lng: 50.1971, zone: 'Asia/Riyadh' },
  // Egypt
  { slug: 'cairo',      cc: 'eg', ar: 'القاهرة',    en: 'Cairo',      ur: 'قاہرہ',      lat: 30.0444, lng: 31.2357, zone: 'Africa/Cairo' },
  { slug: 'alexandria', cc: 'eg', ar: 'الإسكندرية', en: 'Alexandria', ur: 'اسکندریہ',   lat: 31.2001, lng: 29.9187, zone: 'Africa/Cairo' },
  { slug: 'giza',       cc: 'eg', ar: 'الجيزة',     en: 'Giza',       ur: 'جیزہ',       lat: 30.0131, lng: 31.2089, zone: 'Africa/Cairo' },
  { slug: 'mansoura',   cc: 'eg', ar: 'المنصورة',   en: 'Mansoura',   ur: 'منصورہ',     lat: 31.0409, lng: 31.3785, zone: 'Africa/Cairo' },
  { slug: 'tanta',      cc: 'eg', ar: 'طنطا',       en: 'Tanta',      ur: 'طنطا',       lat: 30.7865, lng: 31.0004, zone: 'Africa/Cairo' },
  { slug: 'asyut',      cc: 'eg', ar: 'أسيوط',      en: 'Asyut',      ur: 'اسیوط',      lat: 27.1801, lng: 31.1837, zone: 'Africa/Cairo' },
  { slug: 'aswan',      cc: 'eg', ar: 'أسوان',      en: 'Aswan',      ur: 'اسوان',      lat: 24.0889, lng: 32.8998, zone: 'Africa/Cairo' },
  { slug: 'luxor',      cc: 'eg', ar: 'الأقصر',     en: 'Luxor',      ur: 'اقصر',       lat: 25.6872, lng: 32.6396, zone: 'Africa/Cairo' },
  { slug: 'port-said',  cc: 'eg', ar: 'بورسعيد',    en: 'Port Said',  ur: 'پورٹ سعید',  lat: 31.2653, lng: 32.3019, zone: 'Africa/Cairo' },
  { slug: 'suez',       cc: 'eg', ar: 'السويس',     en: 'Suez',       ur: 'سوئز',       lat: 29.9668, lng: 32.5498, zone: 'Africa/Cairo' },
  // UAE
  { slug: 'dubai',          cc: 'ae', ar: 'دبي',            en: 'Dubai',          ur: 'دبئی',           lat: 25.2048, lng: 55.2708, zone: 'Asia/Dubai' },
  { slug: 'abu-dhabi',      cc: 'ae', ar: 'أبوظبي',         en: 'Abu Dhabi',      ur: 'ابوظہبی',        lat: 24.4539, lng: 54.3773, zone: 'Asia/Dubai' },
  { slug: 'sharjah',        cc: 'ae', ar: 'الشارقة',        en: 'Sharjah',        ur: 'شارجہ',          lat: 25.3463, lng: 55.4209, zone: 'Asia/Dubai' },
  { slug: 'ajman',          cc: 'ae', ar: 'عجمان',          en: 'Ajman',          ur: 'عجمان',          lat: 25.4052, lng: 55.5136, zone: 'Asia/Dubai' },
  { slug: 'al-ain',         cc: 'ae', ar: 'العين',          en: 'Al Ain',         ur: 'العین',          lat: 24.1302, lng: 55.8023, zone: 'Asia/Dubai' },
  { slug: 'ras-al-khaimah', cc: 'ae', ar: 'رأس الخيمة',     en: 'Ras Al Khaimah', ur: 'راس الخیمہ',     lat: 25.7895, lng: 55.9432, zone: 'Asia/Dubai' },
  { slug: 'fujairah',       cc: 'ae', ar: 'الفجيرة',        en: 'Fujairah',       ur: 'فجیرہ',          lat: 25.1288, lng: 56.3265, zone: 'Asia/Dubai' },
  // Kuwait
  { slug: 'kuwait-city', cc: 'kw', ar: 'مدينة الكويت', en: 'Kuwait City', ur: 'کویت سٹی', lat: 29.3759, lng: 47.9774, zone: 'Asia/Kuwait' },
  { slug: 'hawalli',     cc: 'kw', ar: 'حولي',         en: 'Hawalli',     ur: 'حولی',     lat: 29.3328, lng: 48.0286, zone: 'Asia/Kuwait' },
  { slug: 'salmiya',     cc: 'kw', ar: 'السالمية',     en: 'Salmiya',     ur: 'سالمیہ',   lat: 29.3339, lng: 48.0761, zone: 'Asia/Kuwait' },
  // Qatar
  { slug: 'doha',      cc: 'qa', ar: 'الدوحة',  en: 'Doha',      ur: 'دوحہ',     lat: 25.2854, lng: 51.5310, zone: 'Asia/Qatar' },
  { slug: 'al-rayyan', cc: 'qa', ar: 'الريان',  en: 'Al Rayyan', ur: 'الریان',   lat: 25.2919, lng: 51.4244, zone: 'Asia/Qatar' },
  { slug: 'al-wakrah', cc: 'qa', ar: 'الوكرة',  en: 'Al Wakrah', ur: 'الوکرہ',   lat: 25.1715, lng: 51.6034, zone: 'Asia/Qatar' },
  // Bahrain
  { slug: 'manama',   cc: 'bh', ar: 'المنامة', en: 'Manama',   ur: 'منامہ',  lat: 26.2285, lng: 50.5860, zone: 'Asia/Bahrain' },
  { slug: 'muharraq', cc: 'bh', ar: 'المحرق',  en: 'Muharraq', ur: 'محرق',   lat: 26.2572, lng: 50.6119, zone: 'Asia/Bahrain' },
  { slug: 'riffa',    cc: 'bh', ar: 'الرفاع',  en: 'Riffa',    ur: 'رفاع',   lat: 26.1300, lng: 50.5550, zone: 'Asia/Bahrain' },
  // Oman
  { slug: 'muscat',  cc: 'om', ar: 'مسقط',   en: 'Muscat',  ur: 'مسقط',  lat: 23.5880, lng: 58.3829, zone: 'Asia/Muscat' },
  { slug: 'salalah', cc: 'om', ar: 'صلالة',  en: 'Salalah', ur: 'صلالہ', lat: 17.0151, lng: 54.0924, zone: 'Asia/Muscat' },
  { slug: 'sohar',   cc: 'om', ar: 'صحار',   en: 'Sohar',   ur: 'صحار',  lat: 24.3459, lng: 56.7097, zone: 'Asia/Muscat' },
  { slug: 'nizwa',   cc: 'om', ar: 'نزوى',   en: 'Nizwa',   ur: 'نزوی',  lat: 22.9333, lng: 57.5333, zone: 'Asia/Muscat' },
  // Jordan
  { slug: 'amman', cc: 'jo', ar: 'عمّان',   en: 'Amman', ur: 'عمان',   lat: 31.9539, lng: 35.9106, zone: 'Asia/Amman' },
  { slug: 'zarqa', cc: 'jo', ar: 'الزرقاء', en: 'Zarqa', ur: 'زرقاء',  lat: 32.0728, lng: 36.0880, zone: 'Asia/Amman' },
  { slug: 'irbid', cc: 'jo', ar: 'إربد',    en: 'Irbid', ur: 'اربد',   lat: 32.5556, lng: 35.8500, zone: 'Asia/Amman' },
  { slug: 'aqaba', cc: 'jo', ar: 'العقبة',  en: 'Aqaba', ur: 'عقبہ',   lat: 29.5321, lng: 35.0063, zone: 'Asia/Amman' },
  // Palestine
  { slug: 'jerusalem', cc: 'ps', ar: 'القدس',    en: 'Jerusalem', ur: 'القدس',    lat: 31.7683, lng: 35.2137, zone: 'Asia/Jerusalem' },
  { slug: 'gaza',      cc: 'ps', ar: 'غزة',      en: 'Gaza',      ur: 'غزہ',      lat: 31.5017, lng: 34.4668, zone: 'Asia/Gaza' },
  { slug: 'hebron',    cc: 'ps', ar: 'الخليل',   en: 'Hebron',    ur: 'الخلیل',   lat: 31.5326, lng: 35.0998, zone: 'Asia/Hebron' },
  { slug: 'nablus',    cc: 'ps', ar: 'نابلس',    en: 'Nablus',    ur: 'نابلس',    lat: 32.2211, lng: 35.2544, zone: 'Asia/Hebron' },
  { slug: 'ramallah',  cc: 'ps', ar: 'رام الله', en: 'Ramallah',  ur: 'رام اللہ', lat: 31.9038, lng: 35.2034, zone: 'Asia/Hebron' },
  // Lebanon
  { slug: 'beirut',  cc: 'lb', ar: 'بيروت',  en: 'Beirut',  ur: 'بیروت',   lat: 33.8938, lng: 35.5018, zone: 'Asia/Beirut' },
  { slug: 'tripoli', cc: 'lb', ar: 'طرابلس', en: 'Tripoli', ur: 'طرابلس',  lat: 34.4367, lng: 35.8497, zone: 'Asia/Beirut' },
  { slug: 'sidon',   cc: 'lb', ar: 'صيدا',   en: 'Sidon',   ur: 'صیدا',    lat: 33.5606, lng: 35.3758, zone: 'Asia/Beirut' },
  { slug: 'tyre',    cc: 'lb', ar: 'صور',    en: 'Tyre',    ur: 'صور',     lat: 33.2705, lng: 35.2038, zone: 'Asia/Beirut' },
  // Syria
  { slug: 'damascus', cc: 'sy', ar: 'دمشق',    en: 'Damascus', ur: 'دمشق',    lat: 33.5138, lng: 36.2765, zone: 'Asia/Damascus' },
  { slug: 'aleppo',   cc: 'sy', ar: 'حلب',     en: 'Aleppo',   ur: 'حلب',     lat: 36.2021, lng: 37.1343, zone: 'Asia/Damascus' },
  { slug: 'homs',     cc: 'sy', ar: 'حمص',     en: 'Homs',     ur: 'حمص',     lat: 34.7324, lng: 36.7137, zone: 'Asia/Damascus' },
  { slug: 'latakia',  cc: 'sy', ar: 'اللاذقية', en: 'Latakia',  ur: 'لاذقیہ',  lat: 35.5196, lng: 35.7915, zone: 'Asia/Damascus' },
  { slug: 'hama',     cc: 'sy', ar: 'حماة',    en: 'Hama',     ur: 'حماۃ',    lat: 35.1318, lng: 36.7578, zone: 'Asia/Damascus' },
  // Iraq
  { slug: 'baghdad',      cc: 'iq', ar: 'بغداد',       en: 'Baghdad',      ur: 'بغداد',      lat: 33.3152, lng: 44.3661, zone: 'Asia/Baghdad' },
  { slug: 'basra',        cc: 'iq', ar: 'البصرة',      en: 'Basra',        ur: 'بصرہ',       lat: 30.5085, lng: 47.7804, zone: 'Asia/Baghdad' },
  { slug: 'mosul',        cc: 'iq', ar: 'الموصل',      en: 'Mosul',        ur: 'موصل',       lat: 36.3350, lng: 43.1189, zone: 'Asia/Baghdad' },
  { slug: 'erbil',        cc: 'iq', ar: 'أربيل',       en: 'Erbil',        ur: 'اربیل',      lat: 36.1911, lng: 44.0092, zone: 'Asia/Baghdad' },
  { slug: 'najaf',        cc: 'iq', ar: 'النجف',       en: 'Najaf',        ur: 'نجف',        lat: 31.9964, lng: 44.3140, zone: 'Asia/Baghdad' },
  { slug: 'karbala',      cc: 'iq', ar: 'كربلاء',      en: 'Karbala',      ur: 'کربلا',      lat: 32.6160, lng: 44.0249, zone: 'Asia/Baghdad' },
  { slug: 'kirkuk',       cc: 'iq', ar: 'كركوك',       en: 'Kirkuk',       ur: 'کرکوک',      lat: 35.4681, lng: 44.3922, zone: 'Asia/Baghdad' },
  { slug: 'sulaymaniyah', cc: 'iq', ar: 'السليمانية',  en: 'Sulaymaniyah', ur: 'سلیمانیہ',   lat: 35.5570, lng: 45.4357, zone: 'Asia/Baghdad' },
  // Yemen
  { slug: 'sanaa',    cc: 'ye', ar: 'صنعاء',  en: 'Sanaa',    ur: 'صنعاء',  lat: 15.3694, lng: 44.1910, zone: 'Asia/Aden' },
  { slug: 'aden',     cc: 'ye', ar: 'عدن',    en: 'Aden',     ur: 'عدن',    lat: 12.7855, lng: 45.0187, zone: 'Asia/Aden' },
  { slug: 'taiz',     cc: 'ye', ar: 'تعز',    en: 'Taiz',     ur: 'تعز',    lat: 13.5795, lng: 44.0209, zone: 'Asia/Aden' },
  { slug: 'hodeidah', cc: 'ye', ar: 'الحديدة', en: 'Hodeidah', ur: 'حدیدہ',  lat: 14.7978, lng: 42.9545, zone: 'Asia/Aden' },
  // Turkey
  { slug: 'istanbul',  cc: 'tr', ar: 'إسطنبول',   en: 'Istanbul',  ur: 'استنبول',   lat: 41.0082, lng: 28.9784, zone: 'Europe/Istanbul' },
  { slug: 'ankara',    cc: 'tr', ar: 'أنقرة',     en: 'Ankara',    ur: 'انقرہ',     lat: 39.9334, lng: 32.8597, zone: 'Europe/Istanbul' },
  { slug: 'izmir',     cc: 'tr', ar: 'إزمير',     en: 'Izmir',     ur: 'ازمیر',     lat: 38.4237, lng: 27.1428, zone: 'Europe/Istanbul' },
  { slug: 'bursa',     cc: 'tr', ar: 'بورصة',     en: 'Bursa',     ur: 'برسا',      lat: 40.1885, lng: 29.0610, zone: 'Europe/Istanbul' },
  { slug: 'antalya',   cc: 'tr', ar: 'أنطاليا',   en: 'Antalya',   ur: 'انطالیہ',   lat: 36.8969, lng: 30.7133, zone: 'Europe/Istanbul' },
  { slug: 'konya',     cc: 'tr', ar: 'قونية',     en: 'Konya',     ur: 'قونیہ',     lat: 37.8746, lng: 32.4932, zone: 'Europe/Istanbul' },
  { slug: 'gaziantep', cc: 'tr', ar: 'غازي عنتاب', en: 'Gaziantep', ur: 'غازی عنتاب', lat: 37.0662, lng: 37.3833, zone: 'Europe/Istanbul' },
  { slug: 'adana',     cc: 'tr', ar: 'أضنة',      en: 'Adana',     ur: 'اضنہ',      lat: 37.0000, lng: 35.3213, zone: 'Europe/Istanbul' },
  // Iran
  { slug: 'tehran',  cc: 'ir', ar: 'طهران',   en: 'Tehran',  ur: 'تہران',   lat: 35.6892, lng: 51.3890, zone: 'Asia/Tehran' },
  { slug: 'mashhad', cc: 'ir', ar: 'مشهد',    en: 'Mashhad', ur: 'مشہد',    lat: 36.2605, lng: 59.6168, zone: 'Asia/Tehran' },
  { slug: 'isfahan', cc: 'ir', ar: 'أصفهان',  en: 'Isfahan', ur: 'اصفہان',  lat: 32.6546, lng: 51.6680, zone: 'Asia/Tehran' },
  { slug: 'shiraz',  cc: 'ir', ar: 'شيراز',   en: 'Shiraz',  ur: 'شیراز',   lat: 29.5918, lng: 52.5837, zone: 'Asia/Tehran' },
  { slug: 'tabriz',  cc: 'ir', ar: 'تبريز',   en: 'Tabriz',  ur: 'تبریز',   lat: 38.0800, lng: 46.2919, zone: 'Asia/Tehran' },
  { slug: 'qom',     cc: 'ir', ar: 'قم',      en: 'Qom',     ur: 'قم',      lat: 34.6416, lng: 50.8746, zone: 'Asia/Tehran' },
  // Pakistan
  { slug: 'karachi',    cc: 'pk', ar: 'كراتشي',    en: 'Karachi',    ur: 'کراچی',     lat: 24.8607, lng: 67.0011, zone: 'Asia/Karachi' },
  { slug: 'lahore',     cc: 'pk', ar: 'لاهور',     en: 'Lahore',     ur: 'لاہور',     lat: 31.5204, lng: 74.3587, zone: 'Asia/Karachi' },
  { slug: 'islamabad',  cc: 'pk', ar: 'إسلام آباد', en: 'Islamabad',  ur: 'اسلام آباد', lat: 33.6844, lng: 73.0479, zone: 'Asia/Karachi' },
  { slug: 'rawalpindi', cc: 'pk', ar: 'روالبندي',  en: 'Rawalpindi', ur: 'راولپنڈی',  lat: 33.5651, lng: 73.0169, zone: 'Asia/Karachi' },
  { slug: 'faisalabad', cc: 'pk', ar: 'فيصل آباد', en: 'Faisalabad', ur: 'فیصل آباد', lat: 31.4504, lng: 73.1350, zone: 'Asia/Karachi' },
  { slug: 'multan',     cc: 'pk', ar: 'ملتان',     en: 'Multan',     ur: 'ملتان',     lat: 30.1575, lng: 71.5249, zone: 'Asia/Karachi' },
  { slug: 'peshawar',   cc: 'pk', ar: 'بيشاور',    en: 'Peshawar',   ur: 'پشاور',     lat: 34.0151, lng: 71.5249, zone: 'Asia/Karachi' },
  { slug: 'quetta',     cc: 'pk', ar: 'كويتا',     en: 'Quetta',     ur: 'کوئٹہ',     lat: 30.1798, lng: 66.9750, zone: 'Asia/Karachi' },
  { slug: 'hyderabad-pk', cc: 'pk', ar: 'حيدر آباد', en: 'Hyderabad',  ur: 'حیدرآباد',  lat: 25.3960, lng: 68.3578, zone: 'Asia/Karachi' },
  { slug: 'sialkot',    cc: 'pk', ar: 'سيالكوت',   en: 'Sialkot',    ur: 'سیالکوٹ',   lat: 32.4945, lng: 74.5229, zone: 'Asia/Karachi' },
  { slug: 'gujranwala', cc: 'pk', ar: 'غوجرانوالا', en: 'Gujranwala', ur: 'گوجرانوالہ', lat: 32.1877, lng: 74.1945, zone: 'Asia/Karachi' },
  // India
  { slug: 'delhi',     cc: 'in', ar: 'دلهي',      en: 'Delhi',     ur: 'دہلی',      lat: 28.7041, lng: 77.1025, zone: 'Asia/Kolkata' },
  { slug: 'mumbai',    cc: 'in', ar: 'مومباي',    en: 'Mumbai',    ur: 'ممبئی',     lat: 19.0760, lng: 72.8777, zone: 'Asia/Kolkata' },
  { slug: 'hyderabad', cc: 'in', ar: 'حيدر آباد',  en: 'Hyderabad', ur: 'حیدرآباد دکن', lat: 17.3850, lng: 78.4867, zone: 'Asia/Kolkata' },
  { slug: 'kolkata',   cc: 'in', ar: 'كولكاتا',   en: 'Kolkata',   ur: 'کولکاتا',   lat: 22.5726, lng: 88.3639, zone: 'Asia/Kolkata' },
  { slug: 'chennai',   cc: 'in', ar: 'تشيناي',    en: 'Chennai',   ur: 'چنئی',      lat: 13.0827, lng: 80.2707, zone: 'Asia/Kolkata' },
  { slug: 'bangalore', cc: 'in', ar: 'بنغالور',   en: 'Bangalore', ur: 'بنگلور',    lat: 12.9716, lng: 77.5946, zone: 'Asia/Kolkata' },
  { slug: 'lucknow',   cc: 'in', ar: 'لكناو',     en: 'Lucknow',   ur: 'لکھنؤ',     lat: 26.8467, lng: 80.9462, zone: 'Asia/Kolkata' },
  { slug: 'srinagar',  cc: 'in', ar: 'سريناغار',  en: 'Srinagar',  ur: 'سرینگر',    lat: 34.0837, lng: 74.7973, zone: 'Asia/Kolkata' },
  { slug: 'ahmedabad', cc: 'in', ar: 'أحمد آباد',  en: 'Ahmedabad', ur: 'احمد آباد',  lat: 23.0225, lng: 72.5714, zone: 'Asia/Kolkata' },
  // Bangladesh
  { slug: 'dhaka',      cc: 'bd', ar: 'دكا',       en: 'Dhaka',      ur: 'ڈھاکہ',    lat: 23.8103, lng: 90.4125, zone: 'Asia/Dhaka' },
  { slug: 'chittagong', cc: 'bd', ar: 'شيتاغونغ',  en: 'Chittagong', ur: 'چٹاگانگ',  lat: 22.3569, lng: 91.7832, zone: 'Asia/Dhaka' },
  { slug: 'sylhet',     cc: 'bd', ar: 'سيلهت',     en: 'Sylhet',     ur: 'سلہٹ',     lat: 24.8949, lng: 91.8687, zone: 'Asia/Dhaka' },
  { slug: 'khulna',     cc: 'bd', ar: 'خولنا',     en: 'Khulna',     ur: 'کھلنا',    lat: 22.8456, lng: 89.5403, zone: 'Asia/Dhaka' },
  { slug: 'rajshahi',   cc: 'bd', ar: 'راجشاهي',   en: 'Rajshahi',   ur: 'راجشاہی',  lat: 24.3745, lng: 88.6042, zone: 'Asia/Dhaka' },
  // Afghanistan
  { slug: 'kabul',          cc: 'af', ar: 'كابل',        en: 'Kabul',          ur: 'کابل',        lat: 34.5553, lng: 69.2075, zone: 'Asia/Kabul' },
  { slug: 'kandahar',       cc: 'af', ar: 'قندهار',      en: 'Kandahar',       ur: 'قندھار',      lat: 31.6289, lng: 65.7372, zone: 'Asia/Kabul' },
  { slug: 'herat',          cc: 'af', ar: 'هرات',        en: 'Herat',          ur: 'ہرات',        lat: 34.3529, lng: 62.2040, zone: 'Asia/Kabul' },
  { slug: 'mazar-i-sharif', cc: 'af', ar: 'مزار شريف',   en: 'Mazar-i-Sharif', ur: 'مزار شریف',   lat: 36.7090, lng: 67.1109, zone: 'Asia/Kabul' },
  // Indonesia
  { slug: 'jakarta',    cc: 'id', ar: 'جاكرتا',     en: 'Jakarta',    ur: 'جکارتہ',    lat: -6.2088, lng: 106.8456, zone: 'Asia/Jakarta' },
  { slug: 'surabaya',   cc: 'id', ar: 'سورابايا',   en: 'Surabaya',   ur: 'سورابایا',  lat: -7.2575, lng: 112.7521, zone: 'Asia/Jakarta' },
  { slug: 'bandung',    cc: 'id', ar: 'باندونغ',    en: 'Bandung',    ur: 'بانڈونگ',   lat: -6.9175, lng: 107.6191, zone: 'Asia/Jakarta' },
  { slug: 'medan',      cc: 'id', ar: 'ميدان',      en: 'Medan',      ur: 'میدان',     lat: 3.5952,  lng: 98.6722,  zone: 'Asia/Jakarta' },
  { slug: 'makassar',   cc: 'id', ar: 'ماكاسار',    en: 'Makassar',   ur: 'مکاسر',     lat: -5.1477, lng: 119.4327, zone: 'Asia/Makassar' },
  { slug: 'semarang',   cc: 'id', ar: 'سيمارانغ',   en: 'Semarang',   ur: 'سیمارنگ',   lat: -6.9932, lng: 110.4203, zone: 'Asia/Jakarta' },
  { slug: 'palembang',  cc: 'id', ar: 'باليمبانغ',  en: 'Palembang',  ur: 'پالمبنگ',   lat: -2.9761, lng: 104.7754, zone: 'Asia/Jakarta' },
  { slug: 'yogyakarta', cc: 'id', ar: 'يوجياكرتا',  en: 'Yogyakarta', ur: 'یوگیاکرتا', lat: -7.7956, lng: 110.3695, zone: 'Asia/Jakarta' },
  // Malaysia
  { slug: 'kuala-lumpur',  cc: 'my', ar: 'كوالالمبور',   en: 'Kuala Lumpur',  ur: 'کوالالمپور',   lat: 3.1390, lng: 101.6869, zone: 'Asia/Kuala_Lumpur' },
  { slug: 'johor-bahru',   cc: 'my', ar: 'جوهور باهرو',  en: 'Johor Bahru',   ur: 'جوہر بہرو',    lat: 1.4927, lng: 103.7414, zone: 'Asia/Kuala_Lumpur' },
  { slug: 'george-town',   cc: 'my', ar: 'جورج تاون',    en: 'George Town',   ur: 'جارج ٹاؤن',    lat: 5.4141, lng: 100.3288, zone: 'Asia/Kuala_Lumpur' },
  { slug: 'ipoh',          cc: 'my', ar: 'إيبوه',        en: 'Ipoh',          ur: 'ایپوہ',        lat: 4.5975, lng: 101.0901, zone: 'Asia/Kuala_Lumpur' },
  { slug: 'shah-alam',     cc: 'my', ar: 'شاه علم',      en: 'Shah Alam',     ur: 'شاہ عالم',     lat: 3.0733, lng: 101.5185, zone: 'Asia/Kuala_Lumpur' },
  { slug: 'kota-kinabalu', cc: 'my', ar: 'كوتا كينابالو', en: 'Kota Kinabalu', ur: 'کوٹا کنابالو', lat: 5.9804, lng: 116.0735, zone: 'Asia/Kuching' },
  { slug: 'kuching',       cc: 'my', ar: 'كوتشينغ',      en: 'Kuching',       ur: 'کوچنگ',        lat: 1.5535, lng: 110.3593, zone: 'Asia/Kuching' },
  // Singapore & Brunei
  { slug: 'singapore',           cc: 'sg', ar: 'سنغافورة',          en: 'Singapore',           ur: 'سنگاپور',          lat: 1.3521, lng: 103.8198, zone: 'Asia/Singapore' },
  { slug: 'bandar-seri-begawan', cc: 'bn', ar: 'بندر سري بكاوان',   en: 'Bandar Seri Begawan', ur: 'بندر سری بیگاوان', lat: 4.9031, lng: 114.9398, zone: 'Asia/Brunei' },
  // Morocco
  { slug: 'casablanca', cc: 'ma', ar: 'الدار البيضاء', en: 'Casablanca', ur: 'کاسابلانکا', lat: 33.5731, lng: -7.5898, zone: 'Africa/Casablanca' },
  { slug: 'rabat',      cc: 'ma', ar: 'الرباط',        en: 'Rabat',      ur: 'رباط',       lat: 34.0209, lng: -6.8416, zone: 'Africa/Casablanca' },
  { slug: 'fes',        cc: 'ma', ar: 'فاس',           en: 'Fes',        ur: 'فاس',        lat: 34.0181, lng: -5.0078, zone: 'Africa/Casablanca' },
  { slug: 'marrakesh',  cc: 'ma', ar: 'مراكش',         en: 'Marrakesh',  ur: 'مراکش شہر',  lat: 31.6295, lng: -7.9811, zone: 'Africa/Casablanca' },
  { slug: 'tangier',    cc: 'ma', ar: 'طنجة',          en: 'Tangier',    ur: 'طنجہ',       lat: 35.7595, lng: -5.8340, zone: 'Africa/Casablanca' },
  { slug: 'agadir',     cc: 'ma', ar: 'أكادير',        en: 'Agadir',     ur: 'اگادیر',     lat: 30.4278, lng: -9.5981, zone: 'Africa/Casablanca' },
  { slug: 'meknes',     cc: 'ma', ar: 'مكناس',         en: 'Meknes',     ur: 'مکناس',      lat: 33.8731, lng: -5.5407, zone: 'Africa/Casablanca' },
  { slug: 'oujda',      cc: 'ma', ar: 'وجدة',          en: 'Oujda',      ur: 'وجدہ',       lat: 34.6814, lng: -1.9086, zone: 'Africa/Casablanca' },
  // Algeria
  { slug: 'algiers',     cc: 'dz', ar: 'الجزائر العاصمة', en: 'Algiers',     ur: 'الجزائر شہر', lat: 36.7538, lng: 3.0588,  zone: 'Africa/Algiers' },
  { slug: 'oran',        cc: 'dz', ar: 'وهران',           en: 'Oran',        ur: 'وہران',       lat: 35.6969, lng: -0.6331, zone: 'Africa/Algiers' },
  { slug: 'constantine', cc: 'dz', ar: 'قسنطينة',         en: 'Constantine', ur: 'قسنطینہ',     lat: 36.3650, lng: 6.6147,  zone: 'Africa/Algiers' },
  { slug: 'annaba',      cc: 'dz', ar: 'عنابة',           en: 'Annaba',      ur: 'عنابہ',       lat: 36.9009, lng: 7.7660,  zone: 'Africa/Algiers' },
  { slug: 'blida',       cc: 'dz', ar: 'البليدة',         en: 'Blida',       ur: 'بلیدہ',       lat: 36.4701, lng: 2.8277,  zone: 'Africa/Algiers' },
  // Tunisia
  { slug: 'tunis',    cc: 'tn', ar: 'تونس العاصمة', en: 'Tunis',    ur: 'تیونس شہر', lat: 36.8065, lng: 10.1815, zone: 'Africa/Tunis' },
  { slug: 'sfax',     cc: 'tn', ar: 'صفاقس',        en: 'Sfax',     ur: 'صفاقس',     lat: 34.7406, lng: 10.7603, zone: 'Africa/Tunis' },
  { slug: 'sousse',   cc: 'tn', ar: 'سوسة',         en: 'Sousse',   ur: 'سوسہ',      lat: 35.8256, lng: 10.6369, zone: 'Africa/Tunis' },
  { slug: 'kairouan', cc: 'tn', ar: 'القيروان',     en: 'Kairouan', ur: 'قیروان',    lat: 35.6781, lng: 10.0963, zone: 'Africa/Tunis' },
  // Libya
  { slug: 'tripoli-ly', cc: 'ly', ar: 'طرابلس الغرب', en: 'Tripoli',  ur: 'طرابلس (لیبیا)', lat: 32.8872, lng: 13.1913, zone: 'Africa/Tripoli' },
  { slug: 'benghazi',   cc: 'ly', ar: 'بنغازي',        en: 'Benghazi', ur: 'بن غازی',        lat: 32.1167, lng: 20.0667, zone: 'Africa/Tripoli' },
  { slug: 'misrata',    cc: 'ly', ar: 'مصراتة',        en: 'Misrata',  ur: 'مصراتہ',         lat: 32.3754, lng: 15.0925, zone: 'Africa/Tripoli' },
  // Sudan
  { slug: 'khartoum',   cc: 'sd', ar: 'الخرطوم',   en: 'Khartoum',   ur: 'خرطوم',      lat: 15.5007, lng: 32.5599, zone: 'Africa/Khartoum' },
  { slug: 'omdurman',   cc: 'sd', ar: 'أم درمان',  en: 'Omdurman',   ur: 'ام درمان',   lat: 15.6445, lng: 32.4777, zone: 'Africa/Khartoum' },
  { slug: 'port-sudan', cc: 'sd', ar: 'بورتسودان', en: 'Port Sudan', ur: 'پورٹ سوڈان', lat: 19.6158, lng: 37.2164, zone: 'Africa/Khartoum' },
  // Somalia
  { slug: 'mogadishu', cc: 'so', ar: 'مقديشو', en: 'Mogadishu', ur: 'موغادیشو', lat: 2.0469, lng: 45.3182, zone: 'Africa/Mogadishu' },
  { slug: 'hargeisa',  cc: 'so', ar: 'هرجيسا', en: 'Hargeisa',  ur: 'ہرگیسا',   lat: 9.5624, lng: 44.0770, zone: 'Africa/Mogadishu' },
  // Nigeria
  { slug: 'lagos',  cc: 'ng', ar: 'لاغوس',  en: 'Lagos',  ur: 'لاگوس',  lat: 6.5244,  lng: 3.3792, zone: 'Africa/Lagos' },
  { slug: 'kano',   cc: 'ng', ar: 'كانو',   en: 'Kano',   ur: 'کانو',   lat: 12.0022, lng: 8.5920, zone: 'Africa/Lagos' },
  { slug: 'abuja',  cc: 'ng', ar: 'أبوجا',  en: 'Abuja',  ur: 'ابوجا',  lat: 9.0765,  lng: 7.3986, zone: 'Africa/Lagos' },
  { slug: 'ibadan', cc: 'ng', ar: 'إبادان', en: 'Ibadan', ur: 'ابادان', lat: 7.3775,  lng: 3.9470, zone: 'Africa/Lagos' },
  { slug: 'kaduna', cc: 'ng', ar: 'كادونا', en: 'Kaduna', ur: 'کدونا',  lat: 10.5105, lng: 7.4165, zone: 'Africa/Lagos' },
  // Senegal / Ethiopia / Kenya
  { slug: 'dakar',      cc: 'sn', ar: 'داكار',      en: 'Dakar',       ur: 'ڈاکار',      lat: 14.7167, lng: -17.4677, zone: 'Africa/Dakar' },
  { slug: 'touba',      cc: 'sn', ar: 'طوبى',       en: 'Touba',       ur: 'طوبیٰ',      lat: 14.8500, lng: -15.8833, zone: 'Africa/Dakar' },
  { slug: 'addis-ababa', cc: 'et', ar: 'أديس أبابا', en: 'Addis Ababa', ur: 'ادیس ابابا', lat: 9.0250,  lng: 38.7469,  zone: 'Africa/Addis_Ababa' },
  { slug: 'dire-dawa',  cc: 'et', ar: 'ديري داوا', en: 'Dire Dawa',   ur: 'دیرے داوا',  lat: 9.5931,  lng: 41.8661,  zone: 'Africa/Addis_Ababa' },
  { slug: 'nairobi',    cc: 'ke', ar: 'نيروبي',     en: 'Nairobi',     ur: 'نیروبی',     lat: -1.2921, lng: 36.8219,  zone: 'Africa/Nairobi' },
  { slug: 'mombasa',    cc: 'ke', ar: 'مومباسا',    en: 'Mombasa',     ur: 'ممباسا',     lat: -4.0435, lng: 39.6682,  zone: 'Africa/Nairobi' },
  // South Africa
  { slug: 'johannesburg', cc: 'za', ar: 'جوهانسبرغ', en: 'Johannesburg', ur: 'جوہانسبرگ', lat: -26.2041, lng: 28.0473, zone: 'Africa/Johannesburg' },
  { slug: 'cape-town',    cc: 'za', ar: 'كيب تاون',  en: 'Cape Town',    ur: 'کیپ ٹاؤن',  lat: -33.9249, lng: 18.4241, zone: 'Africa/Johannesburg' },
  { slug: 'durban',       cc: 'za', ar: 'ديربان',    en: 'Durban',       ur: 'ڈربن',      lat: -29.8587, lng: 31.0218, zone: 'Africa/Johannesburg' },
  { slug: 'pretoria',     cc: 'za', ar: 'بريتوريا',  en: 'Pretoria',     ur: 'پریٹوریا',  lat: -25.7479, lng: 28.2293, zone: 'Africa/Johannesburg' },
  // United Kingdom
  { slug: 'london',     cc: 'gb', ar: 'لندن',      en: 'London',     ur: 'لندن',      lat: 51.5074, lng: -0.1278, zone: 'Europe/London' },
  { slug: 'birmingham', cc: 'gb', ar: 'برمنغهام',  en: 'Birmingham', ur: 'برمنگھم',   lat: 52.4862, lng: -1.8904, zone: 'Europe/London' },
  { slug: 'manchester', cc: 'gb', ar: 'مانشستر',   en: 'Manchester', ur: 'مانچسٹر',   lat: 53.4808, lng: -2.2426, zone: 'Europe/London' },
  { slug: 'bradford',   cc: 'gb', ar: 'برادفورد',  en: 'Bradford',   ur: 'بریڈفورڈ',  lat: 53.7960, lng: -1.7594, zone: 'Europe/London' },
  { slug: 'leeds',      cc: 'gb', ar: 'ليدز',      en: 'Leeds',      ur: 'لیڈز',      lat: 53.8008, lng: -1.5491, zone: 'Europe/London' },
  { slug: 'leicester',  cc: 'gb', ar: 'ليستر',     en: 'Leicester',  ur: 'لیسٹر',     lat: 52.6369, lng: -1.1398, zone: 'Europe/London' },
  { slug: 'glasgow',    cc: 'gb', ar: 'غلاسكو',    en: 'Glasgow',    ur: 'گلاسگو',    lat: 55.8642, lng: -4.2518, zone: 'Europe/London' },
  { slug: 'sheffield',  cc: 'gb', ar: 'شيفيلد',    en: 'Sheffield',  ur: 'شیفیلڈ',    lat: 53.3811, lng: -1.4701, zone: 'Europe/London' },
  { slug: 'cardiff',    cc: 'gb', ar: 'كارديف',    en: 'Cardiff',    ur: 'کارڈف',     lat: 51.4816, lng: -3.1791, zone: 'Europe/London' },
  // France
  { slug: 'paris',      cc: 'fr', ar: 'باريس',     en: 'Paris',      ur: 'پیرس',      lat: 48.8566, lng: 2.3522, zone: 'Europe/Paris' },
  { slug: 'marseille',  cc: 'fr', ar: 'مرسيليا',   en: 'Marseille',  ur: 'مارسیلز',   lat: 43.2965, lng: 5.3698, zone: 'Europe/Paris' },
  { slug: 'lyon',       cc: 'fr', ar: 'ليون',      en: 'Lyon',       ur: 'لیون',      lat: 45.7640, lng: 4.8357, zone: 'Europe/Paris' },
  { slug: 'toulouse',   cc: 'fr', ar: 'تولوز',     en: 'Toulouse',   ur: 'تولوز',     lat: 43.6047, lng: 1.4442, zone: 'Europe/Paris' },
  { slug: 'lille',      cc: 'fr', ar: 'ليل',       en: 'Lille',      ur: 'لیل',       lat: 50.6292, lng: 3.0573, zone: 'Europe/Paris' },
  { slug: 'nice',       cc: 'fr', ar: 'نيس',       en: 'Nice',       ur: 'نیس',       lat: 43.7102, lng: 7.2620, zone: 'Europe/Paris' },
  { slug: 'strasbourg', cc: 'fr', ar: 'ستراسبورغ', en: 'Strasbourg', ur: 'اسٹراسبرگ', lat: 48.5734, lng: 7.7521, zone: 'Europe/Paris' },
  // Germany
  { slug: 'berlin',     cc: 'de', ar: 'برلين',     en: 'Berlin',     ur: 'برلن',       lat: 52.5200, lng: 13.4050, zone: 'Europe/Berlin' },
  { slug: 'hamburg',    cc: 'de', ar: 'هامبورغ',   en: 'Hamburg',    ur: 'ہیمبرگ',     lat: 53.5511, lng: 9.9937,  zone: 'Europe/Berlin' },
  { slug: 'munich',     cc: 'de', ar: 'ميونخ',     en: 'Munich',     ur: 'میونخ',      lat: 48.1351, lng: 11.5820, zone: 'Europe/Berlin' },
  { slug: 'cologne',    cc: 'de', ar: 'كولونيا',   en: 'Cologne',    ur: 'کولون',      lat: 50.9375, lng: 6.9603,  zone: 'Europe/Berlin' },
  { slug: 'frankfurt',  cc: 'de', ar: 'فرانكفورت', en: 'Frankfurt',  ur: 'فرینکفرٹ',   lat: 50.1109, lng: 8.6821,  zone: 'Europe/Berlin' },
  { slug: 'stuttgart',  cc: 'de', ar: 'شتوتغارت',  en: 'Stuttgart',  ur: 'اشٹٹگارٹ',   lat: 48.7758, lng: 9.1829,  zone: 'Europe/Berlin' },
  { slug: 'dusseldorf', cc: 'de', ar: 'دوسلدورف',  en: 'Düsseldorf', ur: 'ڈوسلڈورف',   lat: 51.2277, lng: 6.7735,  zone: 'Europe/Berlin' },
  // Netherlands & Belgium
  { slug: 'amsterdam', cc: 'nl', ar: 'أمستردام', en: 'Amsterdam', ur: 'ایمسٹرڈیم', lat: 52.3676, lng: 4.9041, zone: 'Europe/Amsterdam' },
  { slug: 'rotterdam', cc: 'nl', ar: 'روتردام',  en: 'Rotterdam', ur: 'روٹرڈیم',   lat: 51.9244, lng: 4.4777, zone: 'Europe/Amsterdam' },
  { slug: 'the-hague', cc: 'nl', ar: 'لاهاي',    en: 'The Hague', ur: 'دی ہیگ',    lat: 52.0705, lng: 4.3007, zone: 'Europe/Amsterdam' },
  { slug: 'utrecht',   cc: 'nl', ar: 'أوترخت',   en: 'Utrecht',   ur: 'یوٹریکٹ',   lat: 52.0907, lng: 5.1214, zone: 'Europe/Amsterdam' },
  { slug: 'brussels',  cc: 'be', ar: 'بروكسل',   en: 'Brussels',  ur: 'برسلز',     lat: 50.8503, lng: 4.3517, zone: 'Europe/Brussels' },
  { slug: 'antwerp',   cc: 'be', ar: 'أنتويرب',  en: 'Antwerp',   ur: 'اینٹورپ',   lat: 51.2194, lng: 4.4025, zone: 'Europe/Brussels' },
  // Spain & Italy
  { slug: 'madrid',    cc: 'es', ar: 'مدريد',    en: 'Madrid',    ur: 'میڈرڈ',    lat: 40.4168, lng: -3.7038, zone: 'Europe/Madrid' },
  { slug: 'barcelona', cc: 'es', ar: 'برشلونة',  en: 'Barcelona', ur: 'بارسلونا', lat: 41.3874, lng: 2.1686,  zone: 'Europe/Madrid' },
  { slug: 'granada',   cc: 'es', ar: 'غرناطة',   en: 'Granada',   ur: 'غرناطہ',   lat: 37.1773, lng: -3.5986, zone: 'Europe/Madrid' },
  { slug: 'valencia',  cc: 'es', ar: 'بلنسية',   en: 'Valencia',  ur: 'والنسیا',  lat: 39.4699, lng: -0.3763, zone: 'Europe/Madrid' },
  { slug: 'rome',      cc: 'it', ar: 'روما',     en: 'Rome',      ur: 'روم',      lat: 41.9028, lng: 12.4964, zone: 'Europe/Rome' },
  { slug: 'milan',     cc: 'it', ar: 'ميلانو',   en: 'Milan',     ur: 'میلان',    lat: 45.4642, lng: 9.1900,  zone: 'Europe/Rome' },
  { slug: 'turin',     cc: 'it', ar: 'تورينو',   en: 'Turin',     ur: 'تیورن',    lat: 45.0703, lng: 7.6869,  zone: 'Europe/Rome' },
  // Nordics + Central Europe
  { slug: 'stockholm',  cc: 'se', ar: 'ستوكهولم', en: 'Stockholm',  ur: 'اسٹاک ہوم', lat: 59.3293, lng: 18.0686, zone: 'Europe/Stockholm' },
  { slug: 'gothenburg', cc: 'se', ar: 'غوتنبرغ',  en: 'Gothenburg', ur: 'گوتھنبرگ',  lat: 57.7089, lng: 11.9746, zone: 'Europe/Stockholm' },
  { slug: 'malmo',      cc: 'se', ar: 'مالمو',    en: 'Malmö',      ur: 'مالمو',     lat: 55.6050, lng: 13.0038, zone: 'Europe/Stockholm' },
  { slug: 'oslo',       cc: 'no', ar: 'أوسلو',    en: 'Oslo',       ur: 'اوسلو',     lat: 59.9139, lng: 10.7522, zone: 'Europe/Oslo' },
  { slug: 'copenhagen', cc: 'dk', ar: 'كوبنهاغن', en: 'Copenhagen', ur: 'کوپن ہیگن', lat: 55.6761, lng: 12.5683, zone: 'Europe/Copenhagen' },
  { slug: 'vienna',     cc: 'at', ar: 'فيينا',    en: 'Vienna',     ur: 'ویانا',     lat: 48.2082, lng: 16.3738, zone: 'Europe/Vienna' },
  { slug: 'zurich',     cc: 'ch', ar: 'زيورخ',    en: 'Zurich',     ur: 'زیورخ',     lat: 47.3769, lng: 8.5417,  zone: 'Europe/Zurich' },
  { slug: 'geneva',     cc: 'ch', ar: 'جنيف',     en: 'Geneva',     ur: 'جنیوا',     lat: 46.2044, lng: 6.1432,  zone: 'Europe/Zurich' },
  // Russia
  { slug: 'moscow',           cc: 'ru', ar: 'موسكو',           en: 'Moscow',           ur: 'ماسکو',          lat: 55.7558, lng: 37.6173, zone: 'Europe/Moscow' },
  { slug: 'saint-petersburg', cc: 'ru', ar: 'سانت بطرسبرغ',    en: 'Saint Petersburg', ur: 'سینٹ پیٹرزبرگ',  lat: 59.9311, lng: 30.3609, zone: 'Europe/Moscow' },
  { slug: 'kazan',            cc: 'ru', ar: 'قازان',           en: 'Kazan',            ur: 'قازان',          lat: 55.8304, lng: 49.0661, zone: 'Europe/Moscow' },
  { slug: 'ufa',              cc: 'ru', ar: 'أوفا',            en: 'Ufa',              ur: 'اوفا',           lat: 54.7388, lng: 55.9721, zone: 'Asia/Yekaterinburg' },
  { slug: 'grozny',           cc: 'ru', ar: 'غروزني',          en: 'Grozny',           ur: 'گروزنی',         lat: 43.3119, lng: 45.6889, zone: 'Europe/Moscow' },
  { slug: 'makhachkala',      cc: 'ru', ar: 'محج قلعة',        en: 'Makhachkala',      ur: 'مخاچکالا',       lat: 42.9849, lng: 47.5047, zone: 'Europe/Moscow' },
  // United States
  { slug: 'new-york',      cc: 'us', ar: 'نيويورك',      en: 'New York',      ur: 'نیویارک',      lat: 40.7128, lng: -74.0060,  zone: 'America/New_York' },
  { slug: 'los-angeles',   cc: 'us', ar: 'لوس أنجلوس',   en: 'Los Angeles',   ur: 'لاس اینجلس',   lat: 34.0522, lng: -118.2437, zone: 'America/Los_Angeles' },
  { slug: 'chicago',       cc: 'us', ar: 'شيكاغو',       en: 'Chicago',       ur: 'شکاگو',        lat: 41.8781, lng: -87.6298,  zone: 'America/Chicago' },
  { slug: 'houston',       cc: 'us', ar: 'هيوستن',       en: 'Houston',       ur: 'ہیوسٹن',       lat: 29.7604, lng: -95.3698,  zone: 'America/Chicago' },
  { slug: 'dallas',        cc: 'us', ar: 'دالاس',        en: 'Dallas',        ur: 'ڈیلس',         lat: 32.7767, lng: -96.7970,  zone: 'America/Chicago' },
  { slug: 'dearborn',      cc: 'us', ar: 'ديربورن',      en: 'Dearborn',      ur: 'ڈیئربورن',     lat: 42.3223, lng: -83.1763,  zone: 'America/Detroit' },
  { slug: 'philadelphia',  cc: 'us', ar: 'فيلادلفيا',    en: 'Philadelphia',  ur: 'فلاڈیلفیا',    lat: 39.9526, lng: -75.1652,  zone: 'America/New_York' },
  { slug: 'washington-dc', cc: 'us', ar: 'واشنطن العاصمة', en: 'Washington, D.C.', ur: 'واشنگٹن ڈی سی', lat: 38.9072, lng: -77.0369, zone: 'America/New_York' },
  { slug: 'boston',        cc: 'us', ar: 'بوسطن',        en: 'Boston',        ur: 'بوسٹن',        lat: 42.3601, lng: -71.0589,  zone: 'America/New_York' },
  { slug: 'atlanta',       cc: 'us', ar: 'أتلانتا',      en: 'Atlanta',       ur: 'اٹلانٹا',      lat: 33.7490, lng: -84.3880,  zone: 'America/New_York' },
  { slug: 'miami',         cc: 'us', ar: 'ميامي',        en: 'Miami',         ur: 'میامی',        lat: 25.7617, lng: -80.1918,  zone: 'America/New_York' },
  { slug: 'minneapolis',   cc: 'us', ar: 'مينيابوليس',   en: 'Minneapolis',   ur: 'منیاپولس',     lat: 44.9778, lng: -93.2650,  zone: 'America/Chicago' },
  { slug: 'seattle',       cc: 'us', ar: 'سياتل',        en: 'Seattle',       ur: 'سیئیٹل',       lat: 47.6062, lng: -122.3321, zone: 'America/Los_Angeles' },
  { slug: 'san-francisco', cc: 'us', ar: 'سان فرانسيسكو', en: 'San Francisco', ur: 'سان فرانسسکو', lat: 37.7749, lng: -122.4194, zone: 'America/Los_Angeles' },
  { slug: 'phoenix',       cc: 'us', ar: 'فينيكس',       en: 'Phoenix',       ur: 'فینکس',        lat: 33.4484, lng: -112.0740, zone: 'America/Phoenix' },
  // Canada
  { slug: 'toronto',     cc: 'ca', ar: 'تورونتو',   en: 'Toronto',     ur: 'ٹورنٹو',    lat: 43.6532, lng: -79.3832,  zone: 'America/Toronto' },
  { slug: 'montreal',    cc: 'ca', ar: 'مونتريال',  en: 'Montreal',    ur: 'مونٹریال',  lat: 45.5019, lng: -73.5674,  zone: 'America/Toronto' },
  { slug: 'vancouver',   cc: 'ca', ar: 'فانكوفر',   en: 'Vancouver',   ur: 'وینکوور',   lat: 49.2827, lng: -123.1207, zone: 'America/Vancouver' },
  { slug: 'ottawa',      cc: 'ca', ar: 'أوتاوا',    en: 'Ottawa',      ur: 'اوٹاوا',    lat: 45.4215, lng: -75.6972,  zone: 'America/Toronto' },
  { slug: 'calgary',     cc: 'ca', ar: 'كالغاري',   en: 'Calgary',     ur: 'کیلگری',    lat: 51.0447, lng: -114.0719, zone: 'America/Edmonton' },
  { slug: 'edmonton',    cc: 'ca', ar: 'إدمونتون',  en: 'Edmonton',    ur: 'ایڈمنٹن',   lat: 53.5461, lng: -113.4938, zone: 'America/Edmonton' },
  { slug: 'mississauga', cc: 'ca', ar: 'ميسيساغا',  en: 'Mississauga', ur: 'مسی ساگا',  lat: 43.5890, lng: -79.6441,  zone: 'America/Toronto' },
  // Australia
  { slug: 'sydney',    cc: 'au', ar: 'سيدني',    en: 'Sydney',    ur: 'سڈنی',     lat: -33.8688, lng: 151.2093, zone: 'Australia/Sydney' },
  { slug: 'melbourne', cc: 'au', ar: 'ملبورن',   en: 'Melbourne', ur: 'میلبورن',  lat: -37.8136, lng: 144.9631, zone: 'Australia/Melbourne' },
  { slug: 'brisbane',  cc: 'au', ar: 'بريزبين',  en: 'Brisbane',  ur: 'برسبین',   lat: -27.4698, lng: 153.0251, zone: 'Australia/Brisbane' },
  { slug: 'perth',     cc: 'au', ar: 'بيرث',     en: 'Perth',     ur: 'پرتھ',     lat: -31.9505, lng: 115.8605, zone: 'Australia/Perth' },
  { slug: 'adelaide',  cc: 'au', ar: 'أديلايد',  en: 'Adelaide',  ur: 'ایڈیلیڈ',  lat: -34.9285, lng: 138.6007, zone: 'Australia/Adelaide' },
  // Central Asia & Caucasus
  { slug: 'baku',      cc: 'az', ar: 'باكو',      en: 'Baku',      ur: 'باکو',      lat: 40.4093, lng: 49.8671, zone: 'Asia/Baku' },
  { slug: 'tashkent',  cc: 'uz', ar: 'طشقند',     en: 'Tashkent',  ur: 'تاشقند',    lat: 41.2995, lng: 69.2401, zone: 'Asia/Tashkent' },
  { slug: 'samarkand', cc: 'uz', ar: 'سمرقند',    en: 'Samarkand', ur: 'سمرقند',    lat: 39.6270, lng: 66.9750, zone: 'Asia/Samarkand' },
  { slug: 'bukhara',   cc: 'uz', ar: 'بخارى',     en: 'Bukhara',   ur: 'بخارا',     lat: 39.7681, lng: 64.4556, zone: 'Asia/Samarkand' },
  { slug: 'almaty',    cc: 'kz', ar: 'ألماتي',    en: 'Almaty',    ur: 'الماتی',    lat: 43.2380, lng: 76.8829, zone: 'Asia/Almaty' },
  { slug: 'astana',    cc: 'kz', ar: 'أستانا',    en: 'Astana',    ur: 'آستانہ',    lat: 51.1605, lng: 71.4704, zone: 'Asia/Almaty' },
  // Balkans
  { slug: 'sarajevo', cc: 'ba', ar: 'سراييفو', en: 'Sarajevo', ur: 'سرائیوو',  lat: 43.8563, lng: 18.4131, zone: 'Europe/Sarajevo' },
  { slug: 'tirana',   cc: 'al', ar: 'تيرانا',  en: 'Tirana',   ur: 'تیرانا',   lat: 41.3275, lng: 19.8187, zone: 'Europe/Tirane' },
  { slug: 'pristina', cc: 'xk', ar: 'بريشتينا', en: 'Pristina', ur: 'پرشتینا',  lat: 42.6629, lng: 21.1655, zone: 'Europe/Belgrade' },
  { slug: 'skopje',   cc: 'mk', ar: 'سكوبيه',  en: 'Skopje',   ur: 'اسکوپیہ',  lat: 41.9973, lng: 21.4280, zone: 'Europe/Skopje' },
  // South & East Asia
  { slug: 'male',    cc: 'mv', ar: 'ماليه',    en: 'Malé',    ur: 'مالے',    lat: 4.1755,  lng: 73.5093,  zone: 'Indian/Maldives' },
  { slug: 'colombo', cc: 'lk', ar: 'كولومبو',  en: 'Colombo', ur: 'کولمبو',  lat: 6.9271,  lng: 79.8612,  zone: 'Asia/Colombo' },
  { slug: 'urumqi',  cc: 'cn', ar: 'أورومتشي', en: 'Urumqi',  ur: 'ارومچی',  lat: 43.8256, lng: 87.6168,  zone: 'Asia/Shanghai' },
  { slug: 'beijing', cc: 'cn', ar: 'بكين',     en: 'Beijing', ur: 'بیجنگ',   lat: 39.9042, lng: 116.4074, zone: 'Asia/Shanghai' },
  { slug: 'manila',  cc: 'ph', ar: 'مانيلا',   en: 'Manila',  ur: 'منیلا',   lat: 14.5995, lng: 120.9842, zone: 'Asia/Manila' },
  { slug: 'bangkok', cc: 'th', ar: 'بانكوك',   en: 'Bangkok', ur: 'بنکاک',   lat: 13.7563, lng: 100.5018, zone: 'Asia/Bangkok' },
  { slug: 'tokyo',   cc: 'jp', ar: 'طوكيو',    en: 'Tokyo',   ur: 'ٹوکیو',   lat: 35.6762, lng: 139.6503, zone: 'Asia/Tokyo' },
];

// ---- helpers ----------------------------------------------------------------
export const countryBySlug = (slug: string) => PT_COUNTRIES.find(c => c.slug === slug);
export const countryByCode = (code: string) => PT_COUNTRIES.find(c => c.code === code);
export const citiesOfCountry = (code: string) => PT_CITIES.filter(c => c.cc === code);
export const cityBySlug = (countrySlug: string, citySlug: string) => {
  const co = countryBySlug(countrySlug);
  if (!co) return undefined;
  return PT_CITIES.find(c => c.cc === co.code && c.slug === citySlug);
};
export const cityMethod = (city: PtCity): MethodId => city.method ?? (countryByCode(city.cc)?.method ?? 'MWL');

// ---- URL helpers -------------------------------------------------------------
export type PtLang = 'ar' | 'en' | 'ur';
export const ptBase = (lang: PtLang) => lang === 'ar' ? '/prayer-times/' : `/${lang}/prayer-times/`;
export const countryPath = (countrySlug: string, lang: PtLang) => `${ptBase(lang)}${countrySlug}/`;
export const cityPath = (countrySlug: string, citySlug: string, lang: PtLang) => `${ptBase(lang)}${countrySlug}/${citySlug}/`;
