// Generated: all countries (names via Intl) + timezone→country map for auto-detect.
export const COUNTRIES = [
  { v: 'ad', ar: 'أندورا', en: 'Andorra', umm: false },
  { v: 'ae', ar: 'الإمارات العربية المتحدة', en: 'United Arab Emirates', umm: true },
  { v: 'af', ar: 'أفغانستان', en: 'Afghanistan', umm: false },
  { v: 'ag', ar: 'أنتيغوا وبربودا', en: 'Antigua & Barbuda', umm: false },
  { v: 'ai', ar: 'أنغويلا', en: 'Anguilla', umm: false },
  { v: 'al', ar: 'ألبانيا', en: 'Albania', umm: false },
  { v: 'am', ar: 'أرمينيا', en: 'Armenia', umm: false },
  { v: 'ao', ar: 'أنغولا', en: 'Angola', umm: false },
  { v: 'aq', ar: 'أنتاركتيكا', en: 'Antarctica', umm: false },
  { v: 'ar', ar: 'الأرجنتين', en: 'Argentina', umm: false },
  { v: 'as', ar: 'ساموا الأمريكية', en: 'American Samoa', umm: false },
  { v: 'at', ar: 'النمسا', en: 'Austria', umm: false },
  { v: 'au', ar: 'أستراليا', en: 'Australia', umm: false },
  { v: 'aw', ar: 'أروبا', en: 'Aruba', umm: false },
  { v: 'ax', ar: 'جزر آلاند', en: 'Åland Islands', umm: false },
  { v: 'az', ar: 'أذربيجان', en: 'Azerbaijan', umm: false },
  { v: 'ba', ar: 'البوسنة والهرسك', en: 'Bosnia & Herzegovina', umm: false },
  { v: 'bb', ar: 'بربادوس', en: 'Barbados', umm: false },
  { v: 'bd', ar: 'بنغلاديش', en: 'Bangladesh', umm: false },
  { v: 'be', ar: 'بلجيكا', en: 'Belgium', umm: false },
  { v: 'bf', ar: 'بوركينا فاسو', en: 'Burkina Faso', umm: false },
  { v: 'bg', ar: 'بلغاريا', en: 'Bulgaria', umm: false },
  { v: 'bh', ar: 'البحرين', en: 'Bahrain', umm: true },
  { v: 'bi', ar: 'بوروندي', en: 'Burundi', umm: false },
  { v: 'bj', ar: 'بنين', en: 'Benin', umm: false },
  { v: 'bl', ar: 'سان بارتليمي', en: 'St. Barthélemy', umm: false },
  { v: 'bm', ar: 'برمودا', en: 'Bermuda', umm: false },
  { v: 'bn', ar: 'بروناي', en: 'Brunei', umm: false },
  { v: 'bo', ar: 'بوليفيا', en: 'Bolivia', umm: false },
  { v: 'bq', ar: 'هولندا الكاريبية', en: 'Caribbean Netherlands', umm: false },
  { v: 'br', ar: 'البرازيل', en: 'Brazil', umm: false },
  { v: 'bs', ar: 'جزر البهاما', en: 'Bahamas', umm: false },
  { v: 'bt', ar: 'بوتان', en: 'Bhutan', umm: false },
  { v: 'bw', ar: 'بوتسوانا', en: 'Botswana', umm: false },
  { v: 'by', ar: 'بيلاروس', en: 'Belarus', umm: false },
  { v: 'bz', ar: 'بليز', en: 'Belize', umm: false },
  { v: 'ca', ar: 'كندا', en: 'Canada', umm: false },
  { v: 'cc', ar: 'جزر كوكوس (كيلينغ)', en: 'Cocos (Keeling) Islands', umm: false },
  { v: 'cd', ar: 'الكونغو - كينشاسا', en: 'Congo - Kinshasa', umm: false },
  { v: 'cf', ar: 'جمهورية أفريقيا الوسطى', en: 'Central African Republic', umm: false },
  { v: 'cg', ar: 'الكونغو - برازافيل', en: 'Congo - Brazzaville', umm: false },
  { v: 'ch', ar: 'سويسرا', en: 'Switzerland', umm: false },
  { v: 'ci', ar: 'ساحل العاج', en: 'Côte d’Ivoire', umm: false },
  { v: 'ck', ar: 'جزر كوك', en: 'Cook Islands', umm: false },
  { v: 'cl', ar: 'تشيلي', en: 'Chile', umm: false },
  { v: 'cm', ar: 'الكاميرون', en: 'Cameroon', umm: false },
  { v: 'cn', ar: 'الصين', en: 'China', umm: false },
  { v: 'co', ar: 'كولومبيا', en: 'Colombia', umm: false },
  { v: 'cr', ar: 'كوستاريكا', en: 'Costa Rica', umm: false },
  { v: 'cu', ar: 'كوبا', en: 'Cuba', umm: false },
  { v: 'cv', ar: 'الرأس الأخضر', en: 'Cape Verde', umm: false },
  { v: 'cw', ar: 'كوراساو', en: 'Curaçao', umm: false },
  { v: 'cx', ar: 'جزيرة كريسماس', en: 'Christmas Island', umm: false },
  { v: 'cy', ar: 'قبرص', en: 'Cyprus', umm: false },
  { v: 'cz', ar: 'التشيك', en: 'Czechia', umm: false },
  { v: 'de', ar: 'ألمانيا', en: 'Germany', umm: false },
  { v: 'dj', ar: 'جيبوتي', en: 'Djibouti', umm: false },
  { v: 'dk', ar: 'الدانمرك', en: 'Denmark', umm: false },
  { v: 'dm', ar: 'دومينيكا', en: 'Dominica', umm: false },
  { v: 'do', ar: 'جمهورية الدومينيكان', en: 'Dominican Republic', umm: false },
  { v: 'dz', ar: 'الجزائر', en: 'Algeria', umm: false },
  { v: 'ec', ar: 'الإكوادور', en: 'Ecuador', umm: false },
  { v: 'ee', ar: 'إستونيا', en: 'Estonia', umm: false },
  { v: 'eg', ar: 'مصر', en: 'Egypt', umm: false },
  { v: 'eh', ar: 'الصحراء الغربية', en: 'Western Sahara', umm: false },
  { v: 'er', ar: 'إريتريا', en: 'Eritrea', umm: false },
  { v: 'es', ar: 'إسبانيا', en: 'Spain', umm: false },
  { v: 'et', ar: 'إثيوبيا', en: 'Ethiopia', umm: false },
  { v: 'fi', ar: 'فنلندا', en: 'Finland', umm: false },
  { v: 'fj', ar: 'فيجي', en: 'Fiji', umm: false },
  { v: 'fk', ar: 'جزر فوكلاند', en: 'Falkland Islands', umm: false },
  { v: 'fm', ar: 'ميكرونيزيا', en: 'Micronesia', umm: false },
  { v: 'fo', ar: 'جزر فارو', en: 'Faroe Islands', umm: false },
  { v: 'fr', ar: 'فرنسا', en: 'France', umm: false },
  { v: 'ga', ar: 'الغابون', en: 'Gabon', umm: false },
  { v: 'gb', ar: 'المملكة المتحدة', en: 'United Kingdom', umm: false },
  { v: 'gd', ar: 'غرينادا', en: 'Grenada', umm: false },
  { v: 'ge', ar: 'جورجيا', en: 'Georgia', umm: false },
  { v: 'gf', ar: 'غويانا الفرنسية', en: 'French Guiana', umm: false },
  { v: 'gg', ar: 'غيرنزي', en: 'Guernsey', umm: false },
  { v: 'gh', ar: 'غانا', en: 'Ghana', umm: false },
  { v: 'gi', ar: 'جبل طارق', en: 'Gibraltar', umm: false },
  { v: 'gl', ar: 'غرينلاند', en: 'Greenland', umm: false },
  { v: 'gm', ar: 'غامبيا', en: 'Gambia', umm: false },
  { v: 'gn', ar: 'غينيا', en: 'Guinea', umm: false },
  { v: 'gp', ar: 'غوادلوب', en: 'Guadeloupe', umm: false },
  { v: 'gq', ar: 'غينيا الاستوائية', en: 'Equatorial Guinea', umm: false },
  { v: 'gr', ar: 'اليونان', en: 'Greece', umm: false },
  { v: 'gs', ar: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', en: 'South Georgia & South Sandwich Islands', umm: false },
  { v: 'gt', ar: 'غواتيمالا', en: 'Guatemala', umm: false },
  { v: 'gu', ar: 'غوام', en: 'Guam', umm: false },
  { v: 'gw', ar: 'غينيا بيساو', en: 'Guinea-Bissau', umm: false },
  { v: 'gy', ar: 'غيانا', en: 'Guyana', umm: false },
  { v: 'hk', ar: 'هونغ كونغ الصينية (منطقة إدارية خاصة)', en: 'Hong Kong SAR China', umm: false },
  { v: 'hm', ar: 'جزيرة هيرد وجزر ماكدونالد', en: 'Heard & McDonald Islands', umm: false },
  { v: 'hn', ar: 'هندوراس', en: 'Honduras', umm: false },
  { v: 'hr', ar: 'كرواتيا', en: 'Croatia', umm: false },
  { v: 'ht', ar: 'هايتي', en: 'Haiti', umm: false },
  { v: 'hu', ar: 'هنغاريا', en: 'Hungary', umm: false },
  { v: 'id', ar: 'إندونيسيا', en: 'Indonesia', umm: false },
  { v: 'ie', ar: 'أيرلندا', en: 'Ireland', umm: false },
  { v: 'il', ar: 'إسرائيل', en: 'Israel', umm: false },
  { v: 'im', ar: 'جزيرة مان', en: 'Isle of Man', umm: false },
  { v: 'in', ar: 'الهند', en: 'India', umm: false },
  { v: 'io', ar: 'الإقليم البريطاني في المحيط الهندي', en: 'British Indian Ocean Territory', umm: false },
  { v: 'iq', ar: 'العراق', en: 'Iraq', umm: false },
  { v: 'ir', ar: 'إيران', en: 'Iran', umm: false },
  { v: 'is', ar: 'آيسلندا', en: 'Iceland', umm: false },
  { v: 'it', ar: 'إيطاليا', en: 'Italy', umm: false },
  { v: 'je', ar: 'جيرسي', en: 'Jersey', umm: false },
  { v: 'jm', ar: 'جامايكا', en: 'Jamaica', umm: false },
  { v: 'jo', ar: 'الأردن', en: 'Jordan', umm: false },
  { v: 'jp', ar: 'اليابان', en: 'Japan', umm: false },
  { v: 'ke', ar: 'كينيا', en: 'Kenya', umm: false },
  { v: 'kg', ar: 'قيرغيزستان', en: 'Kyrgyzstan', umm: false },
  { v: 'kh', ar: 'كمبوديا', en: 'Cambodia', umm: false },
  { v: 'ki', ar: 'كيريباتي', en: 'Kiribati', umm: false },
  { v: 'km', ar: 'جزر القمر', en: 'Comoros', umm: false },
  { v: 'kn', ar: 'سانت كيتس ونيفيس', en: 'St. Kitts & Nevis', umm: false },
  { v: 'kp', ar: 'كوريا الشمالية', en: 'North Korea', umm: false },
  { v: 'kr', ar: 'كوريا الجنوبية', en: 'South Korea', umm: false },
  { v: 'kw', ar: 'الكويت', en: 'Kuwait', umm: true },
  { v: 'ky', ar: 'جزر كايمان', en: 'Cayman Islands', umm: false },
  { v: 'kz', ar: 'كازاخستان', en: 'Kazakhstan', umm: false },
  { v: 'la', ar: 'لاوس', en: 'Laos', umm: false },
  { v: 'lb', ar: 'لبنان', en: 'Lebanon', umm: false },
  { v: 'lc', ar: 'سانت لوسيا', en: 'St. Lucia', umm: false },
  { v: 'li', ar: 'ليختنشتاين', en: 'Liechtenstein', umm: false },
  { v: 'lk', ar: 'سريلانكا', en: 'Sri Lanka', umm: false },
  { v: 'lr', ar: 'ليبيريا', en: 'Liberia', umm: false },
  { v: 'ls', ar: 'ليسوتو', en: 'Lesotho', umm: false },
  { v: 'lt', ar: 'ليتوانيا', en: 'Lithuania', umm: false },
  { v: 'lu', ar: 'لوكسمبورغ', en: 'Luxembourg', umm: false },
  { v: 'lv', ar: 'لاتفيا', en: 'Latvia', umm: false },
  { v: 'ly', ar: 'ليبيا', en: 'Libya', umm: false },
  { v: 'ma', ar: 'المغرب', en: 'Morocco', umm: false },
  { v: 'mc', ar: 'موناكو', en: 'Monaco', umm: false },
  { v: 'md', ar: 'مولدوفا', en: 'Moldova', umm: false },
  { v: 'me', ar: 'الجبل الأسود', en: 'Montenegro', umm: false },
  { v: 'mf', ar: 'سان مارتن', en: 'St. Martin', umm: false },
  { v: 'mg', ar: 'مدغشقر', en: 'Madagascar', umm: false },
  { v: 'mh', ar: 'جزر مارشال', en: 'Marshall Islands', umm: false },
  { v: 'mk', ar: 'مقدونيا الشمالية', en: 'North Macedonia', umm: false },
  { v: 'ml', ar: 'مالي', en: 'Mali', umm: false },
  { v: 'mm', ar: 'ميانمار (بورما)', en: 'Myanmar (Burma)', umm: false },
  { v: 'mn', ar: 'منغوليا', en: 'Mongolia', umm: false },
  { v: 'mo', ar: 'منطقة ماكاو الإدارية الخاصة', en: 'Macao SAR China', umm: false },
  { v: 'mp', ar: 'جزر ماريانا الشمالية', en: 'Northern Mariana Islands', umm: false },
  { v: 'mq', ar: 'جزر المارتينيك', en: 'Martinique', umm: false },
  { v: 'mr', ar: 'موريتانيا', en: 'Mauritania', umm: false },
  { v: 'ms', ar: 'مونتسرات', en: 'Montserrat', umm: false },
  { v: 'mt', ar: 'مالطا', en: 'Malta', umm: false },
  { v: 'mu', ar: 'موريشيوس', en: 'Mauritius', umm: false },
  { v: 'mv', ar: 'جزر المالديف', en: 'Maldives', umm: false },
  { v: 'mw', ar: 'ملاوي', en: 'Malawi', umm: false },
  { v: 'mx', ar: 'المكسيك', en: 'Mexico', umm: false },
  { v: 'my', ar: 'ماليزيا', en: 'Malaysia', umm: false },
  { v: 'mz', ar: 'موزمبيق', en: 'Mozambique', umm: false },
  { v: 'na', ar: 'ناميبيا', en: 'Namibia', umm: false },
  { v: 'nc', ar: 'كاليدونيا الجديدة', en: 'New Caledonia', umm: false },
  { v: 'ne', ar: 'النيجر', en: 'Niger', umm: false },
  { v: 'nf', ar: 'جزيرة نورفولك', en: 'Norfolk Island', umm: false },
  { v: 'ng', ar: 'نيجيريا', en: 'Nigeria', umm: false },
  { v: 'ni', ar: 'نيكاراغوا', en: 'Nicaragua', umm: false },
  { v: 'nl', ar: 'هولندا', en: 'Netherlands', umm: false },
  { v: 'no', ar: 'النرويج', en: 'Norway', umm: false },
  { v: 'np', ar: 'نيبال', en: 'Nepal', umm: false },
  { v: 'nr', ar: 'ناورو', en: 'Nauru', umm: false },
  { v: 'nu', ar: 'نيوي', en: 'Niue', umm: false },
  { v: 'nz', ar: 'نيوزيلندا', en: 'New Zealand', umm: false },
  { v: 'om', ar: 'عُمان', en: 'Oman', umm: true },
  { v: 'pa', ar: 'بنما', en: 'Panama', umm: false },
  { v: 'pe', ar: 'بيرو', en: 'Peru', umm: false },
  { v: 'pf', ar: 'بولينيزيا الفرنسية', en: 'French Polynesia', umm: false },
  { v: 'pg', ar: 'بابوا غينيا الجديدة', en: 'Papua New Guinea', umm: false },
  { v: 'ph', ar: 'الفلبين', en: 'Philippines', umm: false },
  { v: 'pk', ar: 'باكستان', en: 'Pakistan', umm: false },
  { v: 'pl', ar: 'بولندا', en: 'Poland', umm: false },
  { v: 'pm', ar: 'سان بيير ومكويلون', en: 'St. Pierre & Miquelon', umm: false },
  { v: 'pn', ar: 'جزر بيتكيرن', en: 'Pitcairn Islands', umm: false },
  { v: 'pr', ar: 'بورتوريكو', en: 'Puerto Rico', umm: false },
  { v: 'ps', ar: 'الأراضي الفلسطينية', en: 'Palestinian Territories', umm: false },
  { v: 'pt', ar: 'البرتغال', en: 'Portugal', umm: false },
  { v: 'pw', ar: 'بالاو', en: 'Palau', umm: false },
  { v: 'py', ar: 'باراغواي', en: 'Paraguay', umm: false },
  { v: 'qa', ar: 'قطر', en: 'Qatar', umm: true },
  { v: 're', ar: 'روينيون', en: 'Réunion', umm: false },
  { v: 'ro', ar: 'رومانيا', en: 'Romania', umm: false },
  { v: 'rs', ar: 'صربيا', en: 'Serbia', umm: false },
  { v: 'ru', ar: 'روسيا', en: 'Russia', umm: false },
  { v: 'rw', ar: 'رواندا', en: 'Rwanda', umm: false },
  { v: 'sa', ar: 'المملكة العربية السعودية', en: 'Saudi Arabia', umm: true },
  { v: 'sb', ar: 'جزر سليمان', en: 'Solomon Islands', umm: false },
  { v: 'sc', ar: 'سيشل', en: 'Seychelles', umm: false },
  { v: 'sd', ar: 'السودان', en: 'Sudan', umm: false },
  { v: 'se', ar: 'السويد', en: 'Sweden', umm: false },
  { v: 'sg', ar: 'سنغافورة', en: 'Singapore', umm: false },
  { v: 'sh', ar: 'سانت هيلينا', en: 'St. Helena', umm: false },
  { v: 'si', ar: 'سلوفينيا', en: 'Slovenia', umm: false },
  { v: 'sj', ar: 'سفالبارد وجان ماين', en: 'Svalbard & Jan Mayen', umm: false },
  { v: 'sk', ar: 'سلوفاكيا', en: 'Slovakia', umm: false },
  { v: 'sl', ar: 'سيراليون', en: 'Sierra Leone', umm: false },
  { v: 'sm', ar: 'سان مارينو', en: 'San Marino', umm: false },
  { v: 'sn', ar: 'السنغال', en: 'Senegal', umm: false },
  { v: 'so', ar: 'الصومال', en: 'Somalia', umm: false },
  { v: 'sr', ar: 'سورينام', en: 'Suriname', umm: false },
  { v: 'ss', ar: 'جنوب السودان', en: 'South Sudan', umm: false },
  { v: 'st', ar: 'ساو تومي وبرينسيبي', en: 'São Tomé & Príncipe', umm: false },
  { v: 'sv', ar: 'السلفادور', en: 'El Salvador', umm: false },
  { v: 'sx', ar: 'سانت مارتن', en: 'Sint Maarten', umm: false },
  { v: 'sy', ar: 'سوريا', en: 'Syria', umm: false },
  { v: 'sz', ar: 'إسواتيني', en: 'Eswatini', umm: false },
  { v: 'tc', ar: 'جزر توركس وكايكوس', en: 'Turks & Caicos Islands', umm: false },
  { v: 'td', ar: 'تشاد', en: 'Chad', umm: false },
  { v: 'tf', ar: 'الأقاليم الجنوبية الفرنسية', en: 'French Southern Territories', umm: false },
  { v: 'tg', ar: 'توغو', en: 'Togo', umm: false },
  { v: 'th', ar: 'تايلاند', en: 'Thailand', umm: false },
  { v: 'tj', ar: 'طاجيكستان', en: 'Tajikistan', umm: false },
  { v: 'tk', ar: 'توكيلاو', en: 'Tokelau', umm: false },
  { v: 'tl', ar: 'تيمور - ليشتي', en: 'Timor-Leste', umm: false },
  { v: 'tm', ar: 'تركمانستان', en: 'Turkmenistan', umm: false },
  { v: 'tn', ar: 'تونس', en: 'Tunisia', umm: false },
  { v: 'to', ar: 'تونغا', en: 'Tonga', umm: false },
  { v: 'tr', ar: 'تركيا', en: 'Türkiye', umm: false },
  { v: 'tt', ar: 'ترينيداد وتوباغو', en: 'Trinidad & Tobago', umm: false },
  { v: 'tv', ar: 'توفالو', en: 'Tuvalu', umm: false },
  { v: 'tw', ar: 'تايوان', en: 'Taiwan', umm: false },
  { v: 'tz', ar: 'تنزانيا', en: 'Tanzania', umm: false },
  { v: 'ua', ar: 'أوكرانيا', en: 'Ukraine', umm: false },
  { v: 'ug', ar: 'أوغندا', en: 'Uganda', umm: false },
  { v: 'um', ar: 'جزر الولايات المتحدة النائية', en: 'U.S. Outlying Islands', umm: false },
  { v: 'us', ar: 'الولايات المتحدة', en: 'United States', umm: false },
  { v: 'uy', ar: 'أورغواي', en: 'Uruguay', umm: false },
  { v: 'uz', ar: 'أوزبكستان', en: 'Uzbekistan', umm: false },
  { v: 'va', ar: 'الفاتيكان', en: 'Vatican City', umm: false },
  { v: 'vc', ar: 'سانت فنسنت وجزر غرينادين', en: 'St. Vincent & Grenadines', umm: false },
  { v: 've', ar: 'فنزويلا', en: 'Venezuela', umm: false },
  { v: 'vg', ar: 'جزر فيرجن البريطانية', en: 'British Virgin Islands', umm: false },
  { v: 'vi', ar: 'جزر فيرجن الأمريكية', en: 'U.S. Virgin Islands', umm: false },
  { v: 'vn', ar: 'فيتنام', en: 'Vietnam', umm: false },
  { v: 'vu', ar: 'فانواتو', en: 'Vanuatu', umm: false },
  { v: 'wf', ar: 'جزر والس وفوتونا', en: 'Wallis & Futuna', umm: false },
  { v: 'ws', ar: 'ساموا', en: 'Samoa', umm: false },
  { v: 'ye', ar: 'اليمن', en: 'Yemen', umm: false },
  { v: 'yt', ar: 'مايوت', en: 'Mayotte', umm: false },
  { v: 'za', ar: 'جنوب أفريقيا', en: 'South Africa', umm: false },
  { v: 'zm', ar: 'زامبيا', en: 'Zambia', umm: false },
  { v: 'zw', ar: 'زيمبابوي', en: 'Zimbabwe', umm: false },
];

export const TZ_TO_COUNTRY: Record<string, string> = {
  'Africa/Abidjan': 'ci',
  'Africa/Algiers': 'dz',
  'Africa/Asmera': 'er',
  'Africa/Bissau': 'gw',
  'Africa/Cairo': 'eg',
  'Africa/Casablanca': 'ma',
  'Africa/Ceuta': 'es',
  'Africa/El_Aaiun': 'eh',
  'Africa/Johannesburg': 'za',
  'Africa/Juba': 'ss',
  'Africa/Khartoum': 'sd',
  'Africa/Lagos': 'ng',
  'Africa/Maputo': 'mz',
  'Africa/Monrovia': 'lr',
  'Africa/Nairobi': 'ke',
  'Africa/Ndjamena': 'td',
  'Africa/Sao_Tome': 'st',
  'Africa/Tripoli': 'ly',
  'Africa/Tunis': 'tn',
  'Africa/Windhoek': 'na',
  'America/Adak': 'us',
  'America/Anchorage': 'us',
  'America/Araguaina': 'br',
  'America/Argentina/Buenos_Aires': 'ar',
  'America/Argentina/Catamarca': 'ar',
  'America/Argentina/Cordoba': 'ar',
  'America/Argentina/Jujuy': 'ar',
  'America/Argentina/La_Rioja': 'ar',
  'America/Argentina/Mendoza': 'ar',
  'America/Argentina/Rio_Gallegos': 'ar',
  'America/Argentina/Salta': 'ar',
  'America/Argentina/San_Juan': 'ar',
  'America/Argentina/San_Luis': 'ar',
  'America/Argentina/Tucuman': 'ar',
  'America/Argentina/Ushuaia': 'ar',
  'America/Asuncion': 'py',
  'America/Bahia': 'br',
  'America/Bahia_Banderas': 'mx',
  'America/Barbados': 'bb',
  'America/Belem': 'br',
  'America/Belize': 'bz',
  'America/Boa_Vista': 'br',
  'America/Bogota': 'co',
  'America/Boise': 'us',
  'America/Cambridge_Bay': 'ca',
  'America/Campo_Grande': 'br',
  'America/Cancun': 'mx',
  'America/Caracas': 've',
  'America/Cayenne': 'gf',
  'America/Chicago': 'us',
  'America/Chihuahua': 'mx',
  'America/Ciudad_Juarez': 'mx',
  'America/Costa_Rica': 'cr',
  'America/Coyhaique': 'cl',
  'America/Cuiaba': 'br',
  'America/Danmarkshavn': 'gl',
  'America/Dawson': 'ca',
  'America/Dawson_Creek': 'ca',
  'America/Denver': 'us',
  'America/Detroit': 'us',
  'America/Edmonton': 'ca',
  'America/Eirunepe': 'br',
  'America/El_Salvador': 'sv',
  'America/Fort_Nelson': 'ca',
  'America/Fortaleza': 'br',
  'America/Glace_Bay': 'ca',
  'America/Goose_Bay': 'ca',
  'America/Grand_Turk': 'tc',
  'America/Guatemala': 'gt',
  'America/Guayaquil': 'ec',
  'America/Guyana': 'gy',
  'America/Halifax': 'ca',
  'America/Havana': 'cu',
  'America/Hermosillo': 'mx',
  'America/Indiana/Indianapolis': 'us',
  'America/Indiana/Knox': 'us',
  'America/Indiana/Marengo': 'us',
  'America/Indiana/Petersburg': 'us',
  'America/Indiana/Tell_City': 'us',
  'America/Indiana/Vevay': 'us',
  'America/Indiana/Vincennes': 'us',
  'America/Indiana/Winamac': 'us',
  'America/Inuvik': 'ca',
  'America/Iqaluit': 'ca',
  'America/Jamaica': 'jm',
  'America/Juneau': 'us',
  'America/Kentucky/Louisville': 'us',
  'America/Kentucky/Monticello': 'us',
  'America/La_Paz': 'bo',
  'America/Lima': 'pe',
  'America/Los_Angeles': 'us',
  'America/Maceio': 'br',
  'America/Managua': 'ni',
  'America/Manaus': 'br',
  'America/Martinique': 'mq',
  'America/Matamoros': 'mx',
  'America/Mazatlan': 'mx',
  'America/Menominee': 'us',
  'America/Merida': 'mx',
  'America/Metlakatla': 'us',
  'America/Mexico_City': 'mx',
  'America/Miquelon': 'pm',
  'America/Moncton': 'ca',
  'America/Monterrey': 'mx',
  'America/Montevideo': 'uy',
  'America/New_York': 'us',
  'America/Nome': 'us',
  'America/Noronha': 'br',
  'America/North_Dakota/Beulah': 'us',
  'America/North_Dakota/Center': 'us',
  'America/North_Dakota/New_Salem': 'us',
  'America/Nuuk': 'gl',
  'America/Ojinaga': 'mx',
  'America/Panama': 'pa',
  'America/Paramaribo': 'sr',
  'America/Phoenix': 'us',
  'America/Port-au-Prince': 'ht',
  'America/Porto_Velho': 'br',
  'America/Puerto_Rico': 'pr',
  'America/Punta_Arenas': 'cl',
  'America/Rankin_Inlet': 'ca',
  'America/Recife': 'br',
  'America/Regina': 'ca',
  'America/Resolute': 'ca',
  'America/Rio_Branco': 'br',
  'America/Santarem': 'br',
  'America/Santiago': 'cl',
  'America/Santo_Domingo': 'do',
  'America/Sao_Paulo': 'br',
  'America/Scoresbysund': 'gl',
  'America/Sitka': 'us',
  'America/St_Johns': 'ca',
  'America/Swift_Current': 'ca',
  'America/Tegucigalpa': 'hn',
  'America/Thule': 'gl',
  'America/Tijuana': 'mx',
  'America/Toronto': 'ca',
  'America/Vancouver': 'ca',
  'America/Whitehorse': 'ca',
  'America/Winnipeg': 'ca',
  'America/Yakutat': 'us',
  'Antarctica/Casey': 'aq',
  'Antarctica/Davis': 'aq',
  'Antarctica/Macquarie': 'au',
  'Antarctica/Mawson': 'aq',
  'Antarctica/Palmer': 'aq',
  'Antarctica/Rothera': 'aq',
  'Antarctica/Troll': 'aq',
  'Antarctica/Vostok': 'aq',
  'Asia/Aden': 'ye',
  'Asia/Almaty': 'kz',
  'Asia/Amman': 'jo',
  'Asia/Anadyr': 'ru',
  'Asia/Aqtau': 'kz',
  'Asia/Aqtobe': 'kz',
  'Asia/Ashgabat': 'tm',
  'Asia/Atyrau': 'kz',
  'Asia/Baghdad': 'iq',
  'Asia/Bahrain': 'bh',
  'Asia/Baku': 'az',
  'Asia/Bangkok': 'th',
  'Asia/Barnaul': 'ru',
  'Asia/Beirut': 'lb',
  'Asia/Bishkek': 'kg',
  'Asia/Calcutta': 'in',
  'Asia/Chita': 'ru',
  'Asia/Colombo': 'lk',
  'Asia/Damascus': 'sy',
  'Asia/Dhaka': 'bd',
  'Asia/Dili': 'tl',
  'Asia/Dubai': 'ae',
  'Asia/Dushanbe': 'tj',
  'Asia/Famagusta': 'cy',
  'Asia/Gaza': 'ps',
  'Asia/Hebron': 'ps',
  'Asia/Ho_Chi_Minh': 'vn',
  'Asia/Hong_Kong': 'hk',
  'Asia/Hovd': 'mn',
  'Asia/Irkutsk': 'ru',
  'Asia/Istanbul': 'tr',
  'Asia/Jakarta': 'id',
  'Asia/Jayapura': 'id',
  'Asia/Jerusalem': 'il',
  'Asia/Kabul': 'af',
  'Asia/Kamchatka': 'ru',
  'Asia/Karachi': 'pk',
  'Asia/Kathmandu': 'np',
  'Asia/Katmandu': 'np',
  'Asia/Khandyga': 'ru',
  'Asia/Kolkata': 'in',
  'Asia/Krasnoyarsk': 'ru',
  'Asia/Kuching': 'my',
  'Asia/Kuwait': 'kw',
  'Asia/Macau': 'mo',
  'Asia/Magadan': 'ru',
  'Asia/Makassar': 'id',
  'Asia/Manila': 'ph',
  'Asia/Mecca': 'sa',
  'Asia/Medina': 'sa',
  'Asia/Muscat': 'om',
  'Asia/Nicosia': 'cy',
  'Asia/Novokuznetsk': 'ru',
  'Asia/Novosibirsk': 'ru',
  'Asia/Omsk': 'ru',
  'Asia/Oral': 'kz',
  'Asia/Pontianak': 'id',
  'Asia/Pyongyang': 'kp',
  'Asia/Qatar': 'qa',
  'Asia/Qostanay': 'kz',
  'Asia/Qyzylorda': 'kz',
  'Asia/Rangoon': 'mm',
  'Asia/Riyadh': 'sa',
  'Asia/Saigon': 'vn',
  'Asia/Sakhalin': 'ru',
  'Asia/Samarkand': 'uz',
  'Asia/Seoul': 'kr',
  'Asia/Shanghai': 'cn',
  'Asia/Singapore': 'sg',
  'Asia/Srednekolymsk': 'ru',
  'Asia/Taipei': 'tw',
  'Asia/Tashkent': 'uz',
  'Asia/Tbilisi': 'ge',
  'Asia/Tehran': 'ir',
  'Asia/Tel_Aviv': 'ps',
  'Asia/Thimphu': 'bt',
  'Asia/Tokyo': 'jp',
  'Asia/Tomsk': 'ru',
  'Asia/Ulaanbaatar': 'mn',
  'Asia/Urumqi': 'cn',
  'Asia/Ust-Nera': 'ru',
  'Asia/Vladivostok': 'ru',
  'Asia/Yakutsk': 'ru',
  'Asia/Yangon': 'mm',
  'Asia/Yekaterinburg': 'ru',
  'Asia/Yerevan': 'am',
  'Atlantic/Azores': 'pt',
  'Atlantic/Bermuda': 'bm',
  'Atlantic/Canary': 'es',
  'Atlantic/Cape_Verde': 'cv',
  'Atlantic/Faroe': 'fo',
  'Atlantic/Madeira': 'pt',
  'Atlantic/South_Georgia': 'gs',
  'Atlantic/Stanley': 'fk',
  'Australia/Adelaide': 'au',
  'Australia/Brisbane': 'au',
  'Australia/Broken_Hill': 'au',
  'Australia/Darwin': 'au',
  'Australia/Eucla': 'au',
  'Australia/Hobart': 'au',
  'Australia/Lindeman': 'au',
  'Australia/Lord_Howe': 'au',
  'Australia/Melbourne': 'au',
  'Australia/Perth': 'au',
  'Australia/Sydney': 'au',
  'Europe/Andorra': 'ad',
  'Europe/Astrakhan': 'ru',
  'Europe/Athens': 'gr',
  'Europe/Belgrade': 'rs',
  'Europe/Berlin': 'de',
  'Europe/Brussels': 'be',
  'Europe/Bucharest': 'ro',
  'Europe/Budapest': 'hu',
  'Europe/Chisinau': 'md',
  'Europe/Dublin': 'ie',
  'Europe/Gibraltar': 'gi',
  'Europe/Helsinki': 'fi',
  'Europe/Istanbul': 'tr',
  'Europe/Kaliningrad': 'ru',
  'Europe/Kiev': 'ua',
  'Europe/Kirov': 'ru',
  'Europe/Kyiv': 'ua',
  'Europe/Lisbon': 'pt',
  'Europe/London': 'gb',
  'Europe/Madrid': 'es',
  'Europe/Malta': 'mt',
  'Europe/Minsk': 'by',
  'Europe/Moscow': 'ru',
  'Europe/Paris': 'fr',
  'Europe/Prague': 'cz',
  'Europe/Riga': 'lv',
  'Europe/Rome': 'it',
  'Europe/Samara': 'ru',
  'Europe/Saratov': 'ru',
  'Europe/Simferopol': 'ru',
  'Europe/Sofia': 'bg',
  'Europe/Tallinn': 'ee',
  'Europe/Tirane': 'al',
  'Europe/Ulyanovsk': 'ru',
  'Europe/Vienna': 'at',
  'Europe/Vilnius': 'lt',
  'Europe/Volgograd': 'ru',
  'Europe/Warsaw': 'pl',
  'Europe/Zurich': 'ch',
  'Indian/Chagos': 'io',
  'Indian/Maldives': 'mv',
  'Indian/Mauritius': 'mu',
  'Pacific/Apia': 'ws',
  'Pacific/Auckland': 'nz',
  'Pacific/Bougainville': 'pg',
  'Pacific/Chatham': 'nz',
  'Pacific/Easter': 'cl',
  'Pacific/Efate': 'vu',
  'Pacific/Fakaofo': 'tk',
  'Pacific/Fiji': 'fj',
  'Pacific/Galapagos': 'ec',
  'Pacific/Gambier': 'pf',
  'Pacific/Guadalcanal': 'sb',
  'Pacific/Guam': 'gu',
  'Pacific/Honolulu': 'us',
  'Pacific/Kanton': 'ki',
  'Pacific/Kiritimati': 'ki',
  'Pacific/Kosrae': 'fm',
  'Pacific/Kwajalein': 'mh',
  'Pacific/Marquesas': 'pf',
  'Pacific/Nauru': 'nr',
  'Pacific/Niue': 'nu',
  'Pacific/Norfolk': 'nf',
  'Pacific/Noumea': 'nc',
  'Pacific/Pago_Pago': 'as',
  'Pacific/Palau': 'pw',
  'Pacific/Pitcairn': 'pn',
  'Pacific/Port_Moresby': 'pg',
  'Pacific/Rarotonga': 'ck',
  'Pacific/Tahiti': 'pf',
  'Pacific/Tarawa': 'ki',
  'Pacific/Tongatapu': 'to',
};
