// Generated: all countries (ar / en / ur names via Intl.DisplayNames + CLDR)
// + timezone→country map for auto-detect.
export const COUNTRIES = [
  { v: 'ad', ar: 'أندورا', en: 'Andorra', ur: 'انڈورا', umm: false },
  { v: 'ae', ar: 'الإمارات العربية المتحدة', en: 'United Arab Emirates', ur: 'متحدہ عرب امارات', umm: true },
  { v: 'af', ar: 'أفغانستان', en: 'Afghanistan', ur: 'افغانستان', umm: false },
  { v: 'ag', ar: 'أنتيغوا وبربودا', en: 'Antigua & Barbuda', ur: 'انٹیگوا اور باربودا', umm: false },
  { v: 'ai', ar: 'أنغويلا', en: 'Anguilla', ur: 'انگوئیلا', umm: false },
  { v: 'al', ar: 'ألبانيا', en: 'Albania', ur: 'البانیہ', umm: false },
  { v: 'am', ar: 'أرمينيا', en: 'Armenia', ur: 'آرمینیا', umm: false },
  { v: 'ao', ar: 'أنغولا', en: 'Angola', ur: 'انگولا', umm: false },
  { v: 'aq', ar: 'أنتاركتيكا', en: 'Antarctica', ur: 'انٹارکٹیکا', umm: false },
  { v: 'ar', ar: 'الأرجنتين', en: 'Argentina', ur: 'ارجنٹینا', umm: false },
  { v: 'as', ar: 'ساموا الأمريكية', en: 'American Samoa', ur: 'امریکی ساموآ', umm: false },
  { v: 'at', ar: 'النمسا', en: 'Austria', ur: 'آسٹریا', umm: false },
  { v: 'au', ar: 'أستراليا', en: 'Australia', ur: 'آسٹریلیا', umm: false },
  { v: 'aw', ar: 'أروبا', en: 'Aruba', ur: 'اروبا', umm: false },
  { v: 'ax', ar: 'جزر آلاند', en: 'Åland Islands', ur: 'آلینڈ آئلینڈز', umm: false },
  { v: 'az', ar: 'أذربيجان', en: 'Azerbaijan', ur: 'آذربائیجان', umm: false },
  { v: 'ba', ar: 'البوسنة والهرسك', en: 'Bosnia & Herzegovina', ur: 'بوسنیا اور ہرزیگووینا', umm: false },
  { v: 'bb', ar: 'بربادوس', en: 'Barbados', ur: 'بارباڈوس', umm: false },
  { v: 'bd', ar: 'بنغلاديش', en: 'Bangladesh', ur: 'بنگلہ دیش', umm: false },
  { v: 'be', ar: 'بلجيكا', en: 'Belgium', ur: 'بیلجیم', umm: false },
  { v: 'bf', ar: 'بوركينا فاسو', en: 'Burkina Faso', ur: 'برکینا فاسو', umm: false },
  { v: 'bg', ar: 'بلغاريا', en: 'Bulgaria', ur: 'بلغاریہ', umm: false },
  { v: 'bh', ar: 'البحرين', en: 'Bahrain', ur: 'بحرین', umm: true },
  { v: 'bi', ar: 'بوروندي', en: 'Burundi', ur: 'برونڈی', umm: false },
  { v: 'bj', ar: 'بنين', en: 'Benin', ur: 'بینن', umm: false },
  { v: 'bl', ar: 'سان بارتليمي', en: 'St. Barthélemy', ur: 'سینٹ برتھلیمی', umm: false },
  { v: 'bm', ar: 'برمودا', en: 'Bermuda', ur: 'برمودا', umm: false },
  { v: 'bn', ar: 'بروناي', en: 'Brunei', ur: 'برونائی', umm: false },
  { v: 'bo', ar: 'بوليفيا', en: 'Bolivia', ur: 'بولیویا', umm: false },
  { v: 'bq', ar: 'هولندا الكاريبية', en: 'Caribbean Netherlands', ur: 'کریبیائی نیدرلینڈز', umm: false },
  { v: 'br', ar: 'البرازيل', en: 'Brazil', ur: 'برازیل', umm: false },
  { v: 'bs', ar: 'جزر البهاما', en: 'Bahamas', ur: 'بہاماس', umm: false },
  { v: 'bt', ar: 'بوتان', en: 'Bhutan', ur: 'بھوٹان', umm: false },
  { v: 'bw', ar: 'بوتسوانا', en: 'Botswana', ur: 'بوتسوانا', umm: false },
  { v: 'by', ar: 'بيلاروس', en: 'Belarus', ur: 'بیلاروس', umm: false },
  { v: 'bz', ar: 'بليز', en: 'Belize', ur: 'بیلائز', umm: false },
  { v: 'ca', ar: 'كندا', en: 'Canada', ur: 'کینیڈا', umm: false },
  { v: 'cc', ar: 'جزر كوكوس (كيلينغ)', en: 'Cocos (Keeling) Islands', ur: 'کوکوس (کیلنگ) جزائر', umm: false },
  { v: 'cd', ar: 'الكونغو - كينشاسا', en: 'Congo - Kinshasa', ur: 'کانگو - کنشاسا', umm: false },
  { v: 'cf', ar: 'جمهورية أفريقيا الوسطى', en: 'Central African Republic', ur: 'وسط افریقی جمہوریہ', umm: false },
  { v: 'cg', ar: 'الكونغو - برازافيل', en: 'Congo - Brazzaville', ur: 'کانگو - برازاویلے', umm: false },
  { v: 'ch', ar: 'سويسرا', en: 'Switzerland', ur: 'سوئٹزر لینڈ', umm: false },
  { v: 'ci', ar: 'ساحل العاج', en: 'Côte d’Ivoire', ur: 'کوٹ ڈی آئیوری', umm: false },
  { v: 'ck', ar: 'جزر كوك', en: 'Cook Islands', ur: 'کک آئلینڈز', umm: false },
  { v: 'cl', ar: 'تشيلي', en: 'Chile', ur: 'چلی', umm: false },
  { v: 'cm', ar: 'الكاميرون', en: 'Cameroon', ur: 'کیمرون', umm: false },
  { v: 'cn', ar: 'الصين', en: 'China', ur: 'چین', umm: false },
  { v: 'co', ar: 'كولومبيا', en: 'Colombia', ur: 'کولمبیا', umm: false },
  { v: 'cr', ar: 'كوستاريكا', en: 'Costa Rica', ur: 'کوسٹا ریکا', umm: false },
  { v: 'cu', ar: 'كوبا', en: 'Cuba', ur: 'کیوبا', umm: false },
  { v: 'cv', ar: 'الرأس الأخضر', en: 'Cape Verde', ur: 'کیپ ورڈی', umm: false },
  { v: 'cw', ar: 'كوراساو', en: 'Curaçao', ur: 'کیوراکاؤ', umm: false },
  { v: 'cx', ar: 'جزيرة كريسماس', en: 'Christmas Island', ur: 'جزیرہ کرسمس', umm: false },
  { v: 'cy', ar: 'قبرص', en: 'Cyprus', ur: 'قبرص', umm: false },
  { v: 'cz', ar: 'التشيك', en: 'Czechia', ur: 'چیکیا', umm: false },
  { v: 'de', ar: 'ألمانيا', en: 'Germany', ur: 'جرمنی', umm: false },
  { v: 'dj', ar: 'جيبوتي', en: 'Djibouti', ur: 'جبوتی', umm: false },
  { v: 'dk', ar: 'الدانمرك', en: 'Denmark', ur: 'ڈنمارک', umm: false },
  { v: 'dm', ar: 'دومينيكا', en: 'Dominica', ur: 'ڈومنیکا', umm: false },
  { v: 'do', ar: 'جمهورية الدومينيكان', en: 'Dominican Republic', ur: 'جمہوریہ ڈومينيکن', umm: false },
  { v: 'dz', ar: 'الجزائر', en: 'Algeria', ur: 'الجیریا', umm: false },
  { v: 'ec', ar: 'الإكوادور', en: 'Ecuador', ur: 'ایکواڈور', umm: false },
  { v: 'ee', ar: 'إستونيا', en: 'Estonia', ur: 'اسٹونیا', umm: false },
  { v: 'eg', ar: 'مصر', en: 'Egypt', ur: 'مصر', umm: false },
  { v: 'eh', ar: 'الصحراء الغربية', en: 'Western Sahara', ur: 'مغربی صحارا', umm: false },
  { v: 'er', ar: 'إريتريا', en: 'Eritrea', ur: 'اریٹیریا', umm: false },
  { v: 'es', ar: 'إسبانيا', en: 'Spain', ur: 'ہسپانیہ', umm: false },
  { v: 'et', ar: 'إثيوبيا', en: 'Ethiopia', ur: 'ایتھوپیا', umm: false },
  { v: 'fi', ar: 'فنلندا', en: 'Finland', ur: 'فن لینڈ', umm: false },
  { v: 'fj', ar: 'فيجي', en: 'Fiji', ur: 'فجی', umm: false },
  { v: 'fk', ar: 'جزر فوكلاند', en: 'Falkland Islands', ur: 'فاکلینڈ جزائر', umm: false },
  { v: 'fm', ar: 'ميكرونيزيا', en: 'Micronesia', ur: 'مائکرونیشیا', umm: false },
  { v: 'fo', ar: 'جزر فارو', en: 'Faroe Islands', ur: 'جزائر فارو', umm: false },
  { v: 'fr', ar: 'فرنسا', en: 'France', ur: 'فرانس', umm: false },
  { v: 'ga', ar: 'الغابون', en: 'Gabon', ur: 'گیبون', umm: false },
  { v: 'gb', ar: 'المملكة المتحدة', en: 'United Kingdom', ur: 'سلطنت متحدہ', umm: false },
  { v: 'gd', ar: 'غرينادا', en: 'Grenada', ur: 'گریناڈا', umm: false },
  { v: 'ge', ar: 'جورجيا', en: 'Georgia', ur: 'جارجیا', umm: false },
  { v: 'gf', ar: 'غويانا الفرنسية', en: 'French Guiana', ur: 'فرینچ گیانا', umm: false },
  { v: 'gg', ar: 'غيرنزي', en: 'Guernsey', ur: 'گوئرنسی', umm: false },
  { v: 'gh', ar: 'غانا', en: 'Ghana', ur: 'گھانا', umm: false },
  { v: 'gi', ar: 'جبل طارق', en: 'Gibraltar', ur: 'جبل الطارق', umm: false },
  { v: 'gl', ar: 'غرينلاند', en: 'Greenland', ur: 'گرین لینڈ', umm: false },
  { v: 'gm', ar: 'غامبيا', en: 'Gambia', ur: 'گیمبیا', umm: false },
  { v: 'gn', ar: 'غينيا', en: 'Guinea', ur: 'گنی', umm: false },
  { v: 'gp', ar: 'غوادلوب', en: 'Guadeloupe', ur: 'گواڈیلوپ', umm: false },
  { v: 'gq', ar: 'غينيا الاستوائية', en: 'Equatorial Guinea', ur: 'استوائی گیانا', umm: false },
  { v: 'gr', ar: 'اليونان', en: 'Greece', ur: 'یونان', umm: false },
  { v: 'gs', ar: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', en: 'South Georgia & South Sandwich Islands', ur: 'جنوبی جارجیا اور جنوبی سینڈوچ جزائر', umm: false },
  { v: 'gt', ar: 'غواتيمالا', en: 'Guatemala', ur: 'گواٹے مالا', umm: false },
  { v: 'gu', ar: 'غوام', en: 'Guam', ur: 'گوام', umm: false },
  { v: 'gw', ar: 'غينيا بيساو', en: 'Guinea-Bissau', ur: 'گنی بساؤ', umm: false },
  { v: 'gy', ar: 'غيانا', en: 'Guyana', ur: 'گیانا', umm: false },
  { v: 'hk', ar: 'هونغ كونغ الصينية (منطقة إدارية خاصة)', en: 'Hong Kong SAR China', ur: 'ہانگ کانگ SAR چین', umm: false },
  { v: 'hm', ar: 'جزيرة هيرد وجزر ماكدونالد', en: 'Heard & McDonald Islands', ur: 'ہیرڈ جزیرہ و میکڈولینڈ جزائر', umm: false },
  { v: 'hn', ar: 'هندوراس', en: 'Honduras', ur: 'ہونڈاروس', umm: false },
  { v: 'hr', ar: 'كرواتيا', en: 'Croatia', ur: 'کروشیا', umm: false },
  { v: 'ht', ar: 'هايتي', en: 'Haiti', ur: 'ہیٹی', umm: false },
  { v: 'hu', ar: 'هنغاريا', en: 'Hungary', ur: 'ہنگری', umm: false },
  { v: 'id', ar: 'إندونيسيا', en: 'Indonesia', ur: 'انڈونیشیا', umm: false },
  { v: 'ie', ar: 'أيرلندا', en: 'Ireland', ur: 'آئرلینڈ', umm: false },
  { v: 'il', ar: 'إسرائيل', en: 'Israel', ur: 'اسرائیل', umm: false },
  { v: 'im', ar: 'جزيرة مان', en: 'Isle of Man', ur: 'آئل آف مین', umm: false },
  { v: 'in', ar: 'الهند', en: 'India', ur: 'بھارت', umm: false },
  { v: 'io', ar: 'الإقليم البريطاني في المحيط الهندي', en: 'British Indian Ocean Territory', ur: 'برطانوی بحر ہند کا علاقہ', umm: false },
  { v: 'iq', ar: 'العراق', en: 'Iraq', ur: 'عراق', umm: false },
  { v: 'ir', ar: 'إيران', en: 'Iran', ur: 'ایران', umm: false },
  { v: 'is', ar: 'آيسلندا', en: 'Iceland', ur: 'آئس لینڈ', umm: false },
  { v: 'it', ar: 'إيطاليا', en: 'Italy', ur: 'اٹلی', umm: false },
  { v: 'je', ar: 'جيرسي', en: 'Jersey', ur: 'جرسی', umm: false },
  { v: 'jm', ar: 'جامايكا', en: 'Jamaica', ur: 'جمائیکا', umm: false },
  { v: 'jo', ar: 'الأردن', en: 'Jordan', ur: 'اردن', umm: false },
  { v: 'jp', ar: 'اليابان', en: 'Japan', ur: 'جاپان', umm: false },
  { v: 'ke', ar: 'كينيا', en: 'Kenya', ur: 'کینیا', umm: false },
  { v: 'kg', ar: 'قيرغيزستان', en: 'Kyrgyzstan', ur: 'کرغزستان', umm: false },
  { v: 'kh', ar: 'كمبوديا', en: 'Cambodia', ur: 'کمبوڈیا', umm: false },
  { v: 'ki', ar: 'كيريباتي', en: 'Kiribati', ur: 'کریباتی', umm: false },
  { v: 'km', ar: 'جزر القمر', en: 'Comoros', ur: 'کوموروس', umm: false },
  { v: 'kn', ar: 'سانت كيتس ونيفيس', en: 'St. Kitts & Nevis', ur: 'سینٹ کٹس اور نیویس', umm: false },
  { v: 'kp', ar: 'كوريا الشمالية', en: 'North Korea', ur: 'شمالی کوریا', umm: false },
  { v: 'kr', ar: 'كوريا الجنوبية', en: 'South Korea', ur: 'جنوبی کوریا', umm: false },
  { v: 'kw', ar: 'الكويت', en: 'Kuwait', ur: 'کویت', umm: true },
  { v: 'ky', ar: 'جزر كايمان', en: 'Cayman Islands', ur: 'کیمین آئلینڈز', umm: false },
  { v: 'kz', ar: 'كازاخستان', en: 'Kazakhstan', ur: 'قزاخستان', umm: false },
  { v: 'la', ar: 'لاوس', en: 'Laos', ur: 'لاؤس', umm: false },
  { v: 'lb', ar: 'لبنان', en: 'Lebanon', ur: 'لبنان', umm: false },
  { v: 'lc', ar: 'سانت لوسيا', en: 'St. Lucia', ur: 'سینٹ لوسیا', umm: false },
  { v: 'li', ar: 'ليختنشتاين', en: 'Liechtenstein', ur: 'لیشٹنسٹائن', umm: false },
  { v: 'lk', ar: 'سريلانكا', en: 'Sri Lanka', ur: 'سری لنکا', umm: false },
  { v: 'lr', ar: 'ليبيريا', en: 'Liberia', ur: 'لائبیریا', umm: false },
  { v: 'ls', ar: 'ليسوتو', en: 'Lesotho', ur: 'لیسوتھو', umm: false },
  { v: 'lt', ar: 'ليتوانيا', en: 'Lithuania', ur: 'لیتھونیا', umm: false },
  { v: 'lu', ar: 'لوكسمبورغ', en: 'Luxembourg', ur: 'لکسمبرگ', umm: false },
  { v: 'lv', ar: 'لاتفيا', en: 'Latvia', ur: 'لٹویا', umm: false },
  { v: 'ly', ar: 'ليبيا', en: 'Libya', ur: 'لیبیا', umm: false },
  { v: 'ma', ar: 'المغرب', en: 'Morocco', ur: 'مراکش', umm: false },
  { v: 'mc', ar: 'موناكو', en: 'Monaco', ur: 'موناکو', umm: false },
  { v: 'md', ar: 'مولدوفا', en: 'Moldova', ur: 'مالدووا', umm: false },
  { v: 'me', ar: 'الجبل الأسود', en: 'Montenegro', ur: 'مونٹے نیگرو', umm: false },
  { v: 'mf', ar: 'سان مارتن', en: 'St. Martin', ur: 'سینٹ مارٹن', umm: false },
  { v: 'mg', ar: 'مدغشقر', en: 'Madagascar', ur: 'مڈغاسکر', umm: false },
  { v: 'mh', ar: 'جزر مارشال', en: 'Marshall Islands', ur: 'مارشل آئلینڈز', umm: false },
  { v: 'mk', ar: 'مقدونيا الشمالية', en: 'North Macedonia', ur: 'شمالی مقدونیہ', umm: false },
  { v: 'ml', ar: 'مالي', en: 'Mali', ur: 'مالی', umm: false },
  { v: 'mm', ar: 'ميانمار (بورما)', en: 'Myanmar (Burma)', ur: 'میانمار (برما)', umm: false },
  { v: 'mn', ar: 'منغوليا', en: 'Mongolia', ur: 'منگولیا', umm: false },
  { v: 'mo', ar: 'منطقة ماكاو الإدارية الخاصة', en: 'Macao SAR China', ur: 'مکاؤ SAR چین', umm: false },
  { v: 'mp', ar: 'جزر ماريانا الشمالية', en: 'Northern Mariana Islands', ur: 'شمالی ماریانا آئلینڈز', umm: false },
  { v: 'mq', ar: 'جزر المارتينيك', en: 'Martinique', ur: 'مارٹینک', umm: false },
  { v: 'mr', ar: 'موريتانيا', en: 'Mauritania', ur: 'موریطانیہ', umm: false },
  { v: 'ms', ar: 'مونتسرات', en: 'Montserrat', ur: 'مونٹسیراٹ', umm: false },
  { v: 'mt', ar: 'مالطا', en: 'Malta', ur: 'مالٹا', umm: false },
  { v: 'mu', ar: 'موريشيوس', en: 'Mauritius', ur: 'ماریشس', umm: false },
  { v: 'mv', ar: 'جزر المالديف', en: 'Maldives', ur: 'مالدیپ', umm: false },
  { v: 'mw', ar: 'ملاوي', en: 'Malawi', ur: 'ملاوی', umm: false },
  { v: 'mx', ar: 'المكسيك', en: 'Mexico', ur: 'میکسیکو', umm: false },
  { v: 'my', ar: 'ماليزيا', en: 'Malaysia', ur: 'ملائشیا', umm: false },
  { v: 'mz', ar: 'موزمبيق', en: 'Mozambique', ur: 'موزمبیق', umm: false },
  { v: 'na', ar: 'ناميبيا', en: 'Namibia', ur: 'نامیبیا', umm: false },
  { v: 'nc', ar: 'كاليدونيا الجديدة', en: 'New Caledonia', ur: 'نیو کلیڈونیا', umm: false },
  { v: 'ne', ar: 'النيجر', en: 'Niger', ur: 'نائجر', umm: false },
  { v: 'nf', ar: 'جزيرة نورفولك', en: 'Norfolk Island', ur: 'نارفوک آئلینڈ', umm: false },
  { v: 'ng', ar: 'نيجيريا', en: 'Nigeria', ur: 'نائجیریا', umm: false },
  { v: 'ni', ar: 'نيكاراغوا', en: 'Nicaragua', ur: 'نکاراگووا', umm: false },
  { v: 'nl', ar: 'هولندا', en: 'Netherlands', ur: 'نیدر لینڈز', umm: false },
  { v: 'no', ar: 'النرويج', en: 'Norway', ur: 'ناروے', umm: false },
  { v: 'np', ar: 'نيبال', en: 'Nepal', ur: 'نیپال', umm: false },
  { v: 'nr', ar: 'ناورو', en: 'Nauru', ur: 'نؤرو', umm: false },
  { v: 'nu', ar: 'نيوي', en: 'Niue', ur: 'نیئو', umm: false },
  { v: 'nz', ar: 'نيوزيلندا', en: 'New Zealand', ur: 'نیوزی لینڈ', umm: false },
  { v: 'om', ar: 'عُمان', en: 'Oman', ur: 'عمان', umm: true },
  { v: 'pa', ar: 'بنما', en: 'Panama', ur: 'پانامہ', umm: false },
  { v: 'pe', ar: 'بيرو', en: 'Peru', ur: 'پیرو', umm: false },
  { v: 'pf', ar: 'بولينيزيا الفرنسية', en: 'French Polynesia', ur: 'فرانسیسی پولینیشیا', umm: false },
  { v: 'pg', ar: 'بابوا غينيا الجديدة', en: 'Papua New Guinea', ur: 'پاپوآ نیو گنی', umm: false },
  { v: 'ph', ar: 'الفلبين', en: 'Philippines', ur: 'فلپائن', umm: false },
  { v: 'pk', ar: 'باكستان', en: 'Pakistan', ur: 'پاکستان', umm: false },
  { v: 'pl', ar: 'بولندا', en: 'Poland', ur: 'پولینڈ', umm: false },
  { v: 'pm', ar: 'سان بيير ومكويلون', en: 'St. Pierre & Miquelon', ur: 'سینٹ پیئر اور میکلیئون', umm: false },
  { v: 'pn', ar: 'جزر بيتكيرن', en: 'Pitcairn Islands', ur: 'پٹکائرن جزائر', umm: false },
  { v: 'pr', ar: 'بورتوريكو', en: 'Puerto Rico', ur: 'پیورٹو ریکو', umm: false },
  { v: 'ps', ar: 'الأراضي الفلسطينية', en: 'Palestinian Territories', ur: 'فلسطینی خطے', umm: false },
  { v: 'pt', ar: 'البرتغال', en: 'Portugal', ur: 'پرتگال', umm: false },
  { v: 'pw', ar: 'بالاو', en: 'Palau', ur: 'پلاؤ', umm: false },
  { v: 'py', ar: 'باراغواي', en: 'Paraguay', ur: 'پیراگوئے', umm: false },
  { v: 'qa', ar: 'قطر', en: 'Qatar', ur: 'قطر', umm: true },
  { v: 're', ar: 'روينيون', en: 'Réunion', ur: 'ری یونین', umm: false },
  { v: 'ro', ar: 'رومانيا', en: 'Romania', ur: 'رومانیہ', umm: false },
  { v: 'rs', ar: 'صربيا', en: 'Serbia', ur: 'سربیا', umm: false },
  { v: 'ru', ar: 'روسيا', en: 'Russia', ur: 'روس', umm: false },
  { v: 'rw', ar: 'رواندا', en: 'Rwanda', ur: 'روانڈا', umm: false },
  { v: 'sa', ar: 'المملكة العربية السعودية', en: 'Saudi Arabia', ur: 'سعودی عرب', umm: true },
  { v: 'sb', ar: 'جزر سليمان', en: 'Solomon Islands', ur: 'سولومن آئلینڈز', umm: false },
  { v: 'sc', ar: 'سيشل', en: 'Seychelles', ur: 'سشلیز', umm: false },
  { v: 'sd', ar: 'السودان', en: 'Sudan', ur: 'سوڈان', umm: false },
  { v: 'se', ar: 'السويد', en: 'Sweden', ur: 'سویڈن', umm: false },
  { v: 'sg', ar: 'سنغافورة', en: 'Singapore', ur: 'سنگاپور', umm: false },
  { v: 'sh', ar: 'سانت هيلينا', en: 'St. Helena', ur: 'سینٹ ہیلینا', umm: false },
  { v: 'si', ar: 'سلوفينيا', en: 'Slovenia', ur: 'سلووینیا', umm: false },
  { v: 'sj', ar: 'سفالبارد وجان ماين', en: 'Svalbard & Jan Mayen', ur: 'سوالبرڈ اور جان ماین', umm: false },
  { v: 'sk', ar: 'سلوفاكيا', en: 'Slovakia', ur: 'سلوواکیہ', umm: false },
  { v: 'sl', ar: 'سيراليون', en: 'Sierra Leone', ur: 'سیرالیون', umm: false },
  { v: 'sm', ar: 'سان مارينو', en: 'San Marino', ur: 'سان مارینو', umm: false },
  { v: 'sn', ar: 'السنغال', en: 'Senegal', ur: 'سینیگل', umm: false },
  { v: 'so', ar: 'الصومال', en: 'Somalia', ur: 'صومالیہ', umm: false },
  { v: 'sr', ar: 'سورينام', en: 'Suriname', ur: 'سورینام', umm: false },
  { v: 'ss', ar: 'جنوب السودان', en: 'South Sudan', ur: 'جنوبی سوڈان', umm: false },
  { v: 'st', ar: 'ساو تومي وبرينسيبي', en: 'São Tomé & Príncipe', ur: 'ساؤ ٹومے اور پرنسپے', umm: false },
  { v: 'sv', ar: 'السلفادور', en: 'El Salvador', ur: 'ال سلواڈور', umm: false },
  { v: 'sx', ar: 'سانت مارتن', en: 'Sint Maarten', ur: 'سنٹ مارٹن', umm: false },
  { v: 'sy', ar: 'سوريا', en: 'Syria', ur: 'شام', umm: false },
  { v: 'sz', ar: 'إسواتيني', en: 'Eswatini', ur: 'سواتنی', umm: false },
  { v: 'tc', ar: 'جزر توركس وكايكوس', en: 'Turks & Caicos Islands', ur: 'ٹرکس اور کیکوس جزائر', umm: false },
  { v: 'td', ar: 'تشاد', en: 'Chad', ur: 'چاڈ', umm: false },
  { v: 'tf', ar: 'الأقاليم الجنوبية الفرنسية', en: 'French Southern Territories', ur: 'فرانسیسی جنوبی خطے', umm: false },
  { v: 'tg', ar: 'توغو', en: 'Togo', ur: 'ٹوگو', umm: false },
  { v: 'th', ar: 'تايلاند', en: 'Thailand', ur: 'تھائی لینڈ', umm: false },
  { v: 'tj', ar: 'طاجيكستان', en: 'Tajikistan', ur: 'تاجکستان', umm: false },
  { v: 'tk', ar: 'توكيلاو', en: 'Tokelau', ur: 'ٹوکیلاؤ', umm: false },
  { v: 'tl', ar: 'تيمور - ليشتي', en: 'Timor-Leste', ur: 'تیمور لیسٹ', umm: false },
  { v: 'tm', ar: 'تركمانستان', en: 'Turkmenistan', ur: 'ترکمانستان', umm: false },
  { v: 'tn', ar: 'تونس', en: 'Tunisia', ur: 'تونس', umm: false },
  { v: 'to', ar: 'تونغا', en: 'Tonga', ur: 'ٹونگا', umm: false },
  { v: 'tr', ar: 'تركيا', en: 'Türkiye', ur: 'ترکیہ', umm: false },
  { v: 'tt', ar: 'ترينيداد وتوباغو', en: 'Trinidad & Tobago', ur: 'ترینیداد اور ٹوباگو', umm: false },
  { v: 'tv', ar: 'توفالو', en: 'Tuvalu', ur: 'ٹووالو', umm: false },
  { v: 'tw', ar: 'تايوان', en: 'Taiwan', ur: 'تائیوان', umm: false },
  { v: 'tz', ar: 'تنزانيا', en: 'Tanzania', ur: 'تنزانیہ', umm: false },
  { v: 'ua', ar: 'أوكرانيا', en: 'Ukraine', ur: 'یوکرین', umm: false },
  { v: 'ug', ar: 'أوغندا', en: 'Uganda', ur: 'یوگنڈا', umm: false },
  { v: 'um', ar: 'جزر الولايات المتحدة النائية', en: 'U.S. Outlying Islands', ur: 'امریکہ سے باہر کے چھوٹے جزائز', umm: false },
  { v: 'us', ar: 'الولايات المتحدة', en: 'United States', ur: 'ریاست ہائے متحدہ امریکہ', umm: false },
  { v: 'uy', ar: 'أورغواي', en: 'Uruguay', ur: 'یوروگوئے', umm: false },
  { v: 'uz', ar: 'أوزبكستان', en: 'Uzbekistan', ur: 'ازبکستان', umm: false },
  { v: 'va', ar: 'الفاتيكان', en: 'Vatican City', ur: 'ویٹیکن سٹی', umm: false },
  { v: 'vc', ar: 'سانت فنسنت وجزر غرينادين', en: 'St. Vincent & Grenadines', ur: 'سینٹ ونسنٹ اور گرینیڈائنز', umm: false },
  { v: 've', ar: 'فنزويلا', en: 'Venezuela', ur: 'وینزوئیلا', umm: false },
  { v: 'vg', ar: 'جزر فيرجن البريطانية', en: 'British Virgin Islands', ur: 'برٹش ورجن آئلینڈز', umm: false },
  { v: 'vi', ar: 'جزر فيرجن الأمريكية', en: 'U.S. Virgin Islands', ur: 'امریکی ورجن آئلینڈز', umm: false },
  { v: 'vn', ar: 'فيتنام', en: 'Vietnam', ur: 'ویتنام', umm: false },
  { v: 'vu', ar: 'فانواتو', en: 'Vanuatu', ur: 'وینوآٹو', umm: false },
  { v: 'wf', ar: 'جزر والس وفوتونا', en: 'Wallis & Futuna', ur: 'ویلیز اور فیوٹیونا', umm: false },
  { v: 'ws', ar: 'ساموا', en: 'Samoa', ur: 'ساموآ', umm: false },
  { v: 'ye', ar: 'اليمن', en: 'Yemen', ur: 'یمن', umm: false },
  { v: 'yt', ar: 'مايوت', en: 'Mayotte', ur: 'مایوٹ', umm: false },
  { v: 'za', ar: 'جنوب أفريقيا', en: 'South Africa', ur: 'جنوبی افریقہ', umm: false },
  { v: 'zm', ar: 'زامبيا', en: 'Zambia', ur: 'زامبیا', umm: false },
  { v: 'zw', ar: 'زيمبابوي', en: 'Zimbabwe', ur: 'زمبابوے', umm: false },
];

export const TZ_TO_COUNTRY: Record<string, string> = {
  'Africa/Abidjan': 'ci',
  'Africa/Algiers': 'dz',
  'Africa/Asmera': 'er',
  'Africa/Bissau': 'gw',
  'Africa/Cairo': 'eg',
  'Africa/Casablanca': 'ma',
  'Africa/Ceuta': 'es',
  'Africa/El_Aaiun': 'eh',
  'Africa/Johannesburg': 'za',
  'Africa/Juba': 'ss',
  'Africa/Khartoum': 'sd',
  'Africa/Lagos': 'ng',
  'Africa/Maputo': 'mz',
  'Africa/Monrovia': 'lr',
  'Africa/Nairobi': 'ke',
  'Africa/Ndjamena': 'td',
  'Africa/Sao_Tome': 'st',
  'Africa/Tripoli': 'ly',
  'Africa/Tunis': 'tn',
  'Africa/Windhoek': 'na',
  'America/Adak': 'us',
  'America/Anchorage': 'us',
  'America/Araguaina': 'br',
  'America/Argentina/Buenos_Aires': 'ar',
  'America/Argentina/Catamarca': 'ar',
  'America/Argentina/Cordoba': 'ar',
  'America/Argentina/Jujuy': 'ar',
  'America/Argentina/La_Rioja': 'ar',
  'America/Argentina/Mendoza': 'ar',
  'America/Argentina/Rio_Gallegos': 'ar',
  'America/Argentina/Salta': 'ar',
  'America/Argentina/San_Juan': 'ar',
  'America/Argentina/San_Luis': 'ar',
  'America/Argentina/Tucuman': 'ar',
  'America/Argentina/Ushuaia': 'ar',
  'America/Asuncion': 'py',
  'America/Bahia': 'br',
  'America/Bahia_Banderas': 'mx',
  'America/Barbados': 'bb',
  'America/Belem': 'br',
  'America/Belize': 'bz',
  'America/Boa_Vista': 'br',
  'America/Bogota': 'co',
  'America/Boise': 'us',
  'America/Cambridge_Bay': 'ca',
  'America/Campo_Grande': 'br',
  'America/Cancun': 'mx',
  'America/Caracas': 've',
  'America/Cayenne': 'gf',
  'America/Chicago': 'us',
  'America/Chihuahua': 'mx',
  'America/Ciudad_Juarez': 'mx',
  'America/Costa_Rica': 'cr',
  'America/Coyhaique': 'cl',
  'America/Cuiaba': 'br',
  'America/Danmarkshavn': 'gl',
  'America/Dawson': 'ca',
  'America/Dawson_Creek': 'ca',
  'America/Denver': 'us',
  'America/Detroit': 'us',
  'America/Edmonton': 'ca',
  'America/Eirunepe': 'br',
  'America/El_Salvador': 'sv',
  'America/Fort_Nelson': 'ca',
  'America/Fortaleza': 'br',
  'America/Glace_Bay': 'ca',
  'America/Goose_Bay': 'ca',
  'America/Grand_Turk': 'tc',
  'America/Guatemala': 'gt',
  'America/Guayaquil': 'ec',
  'America/Guyana': 'gy',
  'America/Halifax': 'ca',
  'America/Havana': 'cu',
  'America/Hermosillo': 'mx',
  'America/Indiana/Indianapolis': 'us',
  'America/Indiana/Knox': 'us',
  'America/Indiana/Marengo': 'us',
  'America/Indiana/Petersburg': 'us',
  'America/Indiana/Tell_City': 'us',
  'America/Indiana/Vevay': 'us',
  'America/Indiana/Vincennes': 'us',
  'America/Indiana/Winamac': 'us',
  'America/Inuvik': 'ca',
  'America/Iqaluit': 'ca',
  'America/Jamaica': 'jm',
  'America/Juneau': 'us',
  'America/Kentucky/Louisville': 'us',
  'America/Kentucky/Monticello': 'us',
  'America/La_Paz': 'bo',
  'America/Lima': 'pe',
  'America/Los_Angeles': 'us',
  'America/Maceio': 'br',
  'America/Managua': 'ni',
  'America/Manaus': 'br',
  'America/Martinique': 'mq',
  'America/Matamoros': 'mx',
  'America/Mazatlan': 'mx',
  'America/Menominee': 'us',
  'America/Merida': 'mx',
  'America/Metlakatla': 'us',
  'America/Mexico_City': 'mx',
  'America/Miquelon': 'pm',
  'America/Moncton': 'ca',
  'America/Monterrey': 'mx',
  'America/Montevideo': 'uy',
  'America/New_York': 'us',
  'America/Nome': 'us',
  'America/Noronha': 'br',
  'America/North_Dakota/Beulah': 'us',
  'America/North_Dakota/Center': 'us',
  'America/North_Dakota/New_Salem': 'us',
  'America/Nuuk': 'gl',
  'America/Ojinaga': 'mx',
  'America/Panama': 'pa',
  'America/Paramaribo': 'sr',
  'America/Phoenix': 'us',
  'America/Port-au-Prince': 'ht',
  'America/Porto_Velho': 'br',
  'America/Puerto_Rico': 'pr',
  'America/Punta_Arenas': 'cl',
  'America/Rankin_Inlet': 'ca',
  'America/Recife': 'br',
  'America/Regina': 'ca',
  'America/Resolute': 'ca',
  'America/Rio_Branco': 'br',
  'America/Santarem': 'br',
  'America/Santiago': 'cl',
  'America/Santo_Domingo': 'do',
  'America/Sao_Paulo': 'br',
  'America/Scoresbysund': 'gl',
  'America/Sitka': 'us',
  'America/St_Johns': 'ca',
  'America/Swift_Current': 'ca',
  'America/Tegucigalpa': 'hn',
  'America/Thule': 'gl',
  'America/Tijuana': 'mx',
  'America/Toronto': 'ca',
  'America/Vancouver': 'ca',
  'America/Whitehorse': 'ca',
  'America/Winnipeg': 'ca',
  'America/Yakutat': 'us',
  'Antarctica/Casey': 'aq',
  'Antarctica/Davis': 'aq',
  'Antarctica/Macquarie': 'au',
  'Antarctica/Mawson': 'aq',
  'Antarctica/Palmer': 'aq',
  'Antarctica/Rothera': 'aq',
  'Antarctica/Troll': 'aq',
  'Antarctica/Vostok': 'aq',
  'Asia/Aden': 'ye',
  'Asia/Almaty': 'kz',
  'Asia/Amman': 'jo',
  'Asia/Anadyr': 'ru',
  'Asia/Aqtau': 'kz',
  'Asia/Aqtobe': 'kz',
  'Asia/Ashgabat': 'tm',
  'Asia/Atyrau': 'kz',
  'Asia/Baghdad': 'iq',
  'Asia/Bahrain': 'bh',
  'Asia/Baku': 'az',
  'Asia/Bangkok': 'th',
  'Asia/Barnaul': 'ru',
  'Asia/Beirut': 'lb',
  'Asia/Bishkek': 'kg',
  'Asia/Calcutta': 'in',
  'Asia/Chita': 'ru',
  'Asia/Colombo': 'lk',
  'Asia/Damascus': 'sy',
  'Asia/Dhaka': 'bd',
  'Asia/Dili': 'tl',
  'Asia/Dubai': 'ae',
  'Asia/Dushanbe': 'tj',
  'Asia/Famagusta': 'cy',
  'Asia/Gaza': 'ps',
  'Asia/Hebron': 'ps',
  'Asia/Ho_Chi_Minh': 'vn',
  'Asia/Hong_Kong': 'hk',
  'Asia/Hovd': 'mn',
  'Asia/Irkutsk': 'ru',
  'Asia/Istanbul': 'tr',
  'Asia/Jakarta': 'id',
  'Asia/Jayapura': 'id',
  'Asia/Jerusalem': 'il',
  'Asia/Kabul': 'af',
  'Asia/Kamchatka': 'ru',
  'Asia/Karachi': 'pk',
  'Asia/Kathmandu': 'np',
  'Asia/Katmandu': 'np',
  'Asia/Khandyga': 'ru',
  'Asia/Kolkata': 'in',
  'Asia/Krasnoyarsk': 'ru',
  'Asia/Kuching': 'my',
  'Asia/Kuwait': 'kw',
  'Asia/Macau': 'mo',
  'Asia/Magadan': 'ru',
  'Asia/Makassar': 'id',
  'Asia/Manila': 'ph',
  'Asia/Mecca': 'sa',
  'Asia/Medina': 'sa',
  'Asia/Muscat': 'om',
  'Asia/Nicosia': 'cy',
  'Asia/Novokuznetsk': 'ru',
  'Asia/Novosibirsk': 'ru',
  'Asia/Omsk': 'ru',
  'Asia/Oral': 'kz',
  'Asia/Pontianak': 'id',
  'Asia/Pyongyang': 'kp',
  'Asia/Qatar': 'qa',
  'Asia/Qostanay': 'kz',
  'Asia/Qyzylorda': 'kz',
  'Asia/Rangoon': 'mm',
  'Asia/Riyadh': 'sa',
  'Asia/Saigon': 'vn',
  'Asia/Sakhalin': 'ru',
  'Asia/Samarkand': 'uz',
  'Asia/Seoul': 'kr',
  'Asia/Shanghai': 'cn',
  'Asia/Singapore': 'sg',
  'Asia/Srednekolymsk': 'ru',
  'Asia/Taipei': 'tw',
  'Asia/Tashkent': 'uz',
  'Asia/Tbilisi': 'ge',
  'Asia/Tehran': 'ir',
  'Asia/Tel_Aviv': 'ps',
  'Asia/Thimphu': 'bt',
  'Asia/Tokyo': 'jp',
  'Asia/Tomsk': 'ru',
  'Asia/Ulaanbaatar': 'mn',
  'Asia/Urumqi': 'cn',
  'Asia/Ust-Nera': 'ru',
  'Asia/Vladivostok': 'ru',
  'Asia/Yakutsk': 'ru',
  'Asia/Yangon': 'mm',
  'Asia/Yekaterinburg': 'ru',
  'Asia/Yerevan': 'am',
  'Atlantic/Azores': 'pt',
  'Atlantic/Bermuda': 'bm',
  'Atlantic/Canary': 'es',
  'Atlantic/Cape_Verde': 'cv',
  'Atlantic/Faroe': 'fo',
  'Atlantic/Madeira': 'pt',
  'Atlantic/South_Georgia': 'gs',
  'Atlantic/Stanley': 'fk',
  'Australia/Adelaide': 'au',
  'Australia/Brisbane': 'au',
  'Australia/Broken_Hill': 'au',
  'Australia/Darwin': 'au',
  'Australia/Eucla': 'au',
  'Australia/Hobart': 'au',
  'Australia/Lindeman': 'au',
  'Australia/Lord_Howe': 'au',
  'Australia/Melbourne': 'au',
  'Australia/Perth': 'au',
  'Australia/Sydney': 'au',
  'Europe/Andorra': 'ad',
  'Europe/Astrakhan': 'ru',
  'Europe/Athens': 'gr',
  'Europe/Belgrade': 'rs',
  'Europe/Berlin': 'de',
  'Europe/Brussels': 'be',
  'Europe/Bucharest': 'ro',
  'Europe/Budapest': 'hu',
  'Europe/Chisinau': 'md',
  'Europe/Dublin': 'ie',
  'Europe/Gibraltar': 'gi',
  'Europe/Helsinki': 'fi',
  'Europe/Istanbul': 'tr',
  'Europe/Kaliningrad': 'ru',
  'Europe/Kiev': 'ua',
  'Europe/Kirov': 'ru',
  'Europe/Kyiv': 'ua',
  'Europe/Lisbon': 'pt',
  'Europe/London': 'gb',
  'Europe/Madrid': 'es',
  'Europe/Malta': 'mt',
  'Europe/Minsk': 'by',
  'Europe/Moscow': 'ru',
  'Europe/Paris': 'fr',
  'Europe/Prague': 'cz',
  'Europe/Riga': 'lv',
  'Europe/Rome': 'it',
  'Europe/Samara': 'ru',
  'Europe/Saratov': 'ru',
  'Europe/Simferopol': 'ru',
  'Europe/Sofia': 'bg',
  'Europe/Tallinn': 'ee',
  'Europe/Tirane': 'al',
  'Europe/Ulyanovsk': 'ru',
  'Europe/Vienna': 'at',
  'Europe/Vilnius': 'lt',
  'Europe/Volgograd': 'ru',
  'Europe/Warsaw': 'pl',
  'Europe/Zurich': 'ch',
  'Indian/Chagos': 'io',
  'Indian/Maldives': 'mv',
  'Indian/Mauritius': 'mu',
  'Pacific/Apia': 'ws',
  'Pacific/Auckland': 'nz',
  'Pacific/Bougainville': 'pg',
  'Pacific/Chatham': 'nz',
  'Pacific/Easter': 'cl',
  'Pacific/Efate': 'vu',
  'Pacific/Fakaofo': 'tk',
  'Pacific/Fiji': 'fj',
  'Pacific/Galapagos': 'ec',
  'Pacific/Gambier': 'pf',
  'Pacific/Guadalcanal': 'sb',
  'Pacific/Guam': 'gu',
  'Pacific/Honolulu': 'us',
  'Pacific/Kanton': 'ki',
  'Pacific/Kiritimati': 'ki',
  'Pacific/Kosrae': 'fm',
  'Pacific/Kwajalein': 'mh',
  'Pacific/Marquesas': 'pf',
  'Pacific/Nauru': 'nr',
  'Pacific/Niue': 'nu',
  'Pacific/Norfolk': 'nf',
  'Pacific/Noumea': 'nc',
  'Pacific/Pago_Pago': 'as',
  'Pacific/Palau': 'pw',
  'Pacific/Pitcairn': 'pn',
  'Pacific/Port_Moresby': 'pg',
  'Pacific/Rarotonga': 'ck',
  'Pacific/Tahiti': 'pf',
  'Pacific/Tarawa': 'ki',
  'Pacific/Tongatapu': 'to',
};
