// Curated authentic hadiths — exclusively from Sahih al-Bukhari & Sahih Muslim
// (متفق عليه / رواه البخاري / رواه مسلم). Shown one per day, rotating by day-of-year.
export interface Hadith { ar: string; arSrc: string; en: string; enSrc: string; }

export const HADITHS: Hadith[] = [
  { ar: 'إنَّما الأعمالُ بالنِّيّاتِ، وإنَّما لكلِّ امرئٍ ما نَوى', arSrc: 'متفق عليه', en: 'Actions are but by intentions, and every person will have only what they intended.', enSrc: 'Bukhari & Muslim' },
  { ar: 'مَن كان يؤمنُ باللهِ واليومِ الآخِرِ فليَقُلْ خيرًا أو ليَصمُتْ', arSrc: 'متفق عليه', en: 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.', enSrc: 'Bukhari & Muslim' },
  { ar: 'المسلمُ مَن سَلِمَ المسلمونَ من لسانِه ويدِه', arSrc: 'متفق عليه', en: 'The Muslim is the one from whose tongue and hand other Muslims are safe.', enSrc: 'Bukhari & Muslim' },
  { ar: 'لا يؤمنُ أحدُكم حتى يُحبَّ لأخيهِ ما يُحبُّ لنفسِه', arSrc: 'متفق عليه', en: 'None of you truly believes until he loves for his brother what he loves for himself.', enSrc: 'Bukhari & Muslim' },
  { ar: 'الدِّينُ النَّصيحةُ', arSrc: 'رواه مسلم', en: 'Religion is sincerity and well-wishing.', enSrc: 'Muslim' },
  { ar: 'الطُّهورُ شَطرُ الإيمانِ', arSrc: 'رواه مسلم', en: 'Purity is half of faith.', enSrc: 'Muslim' },
  { ar: 'الكلمةُ الطيِّبةُ صدقةٌ', arSrc: 'متفق عليه', en: 'A good word is a charity.', enSrc: 'Bukhari & Muslim' },
  { ar: 'مَن لا يَرحمُ الناسَ لا يَرحمُه اللهُ', arSrc: 'متفق عليه', en: 'Whoever does not show mercy to people, Allah will not show mercy to him.', enSrc: 'Bukhari & Muslim' },
  { ar: 'إنَّ اللهَ رفيقٌ يُحبُّ الرِّفقَ في الأمرِ كلِّه', arSrc: 'متفق عليه', en: 'Allah is gentle and loves gentleness in all matters.', enSrc: 'Bukhari & Muslim' },
  { ar: 'خيرُكم مَن تعلَّمَ القرآنَ وعلَّمَه', arSrc: 'رواه البخاري', en: 'The best of you are those who learn the Quran and teach it.', enSrc: 'Bukhari' },
  { ar: 'مَن سلكَ طريقًا يلتمِسُ فيه عِلمًا، سهَّلَ اللهُ له به طريقًا إلى الجنةِ', arSrc: 'رواه مسلم', en: 'Whoever travels a path seeking knowledge, Allah will make easy for him a path to Paradise.', enSrc: 'Muslim' },
  { ar: 'إنَّ اللهَ كتبَ الإحسانَ على كلِّ شيءٍ', arSrc: 'رواه مسلم', en: 'Allah has prescribed excellence (ihsan) in all things.', enSrc: 'Muslim' },
  { ar: 'مَن نفَّسَ عن مؤمنٍ كُربةً من كُرَبِ الدنيا، نفَّسَ اللهُ عنه كُربةً من كُرَبِ يومِ القيامةِ', arSrc: 'رواه مسلم', en: 'Whoever relieves a believer of a hardship of this world, Allah will relieve him of a hardship on the Day of Resurrection.', enSrc: 'Muslim' },
  { ar: 'بشِّروا ولا تُنفِّروا، ويسِّروا ولا تُعسِّروا', arSrc: 'متفق عليه', en: 'Give glad tidings and do not repel; make things easy and do not make them hard.', enSrc: 'Bukhari & Muslim' },
  { ar: 'أحبُّ الأعمالِ إلى اللهِ أدْوَمُها وإن قلَّ', arSrc: 'متفق عليه', en: 'The most beloved deeds to Allah are those done consistently, even if small.', enSrc: 'Bukhari & Muslim' },
  { ar: 'إذا ماتَ ابنُ آدمَ انقطعَ عملُه إلا من ثلاثٍ: صدقةٍ جاريةٍ، أو علمٍ يُنتفَعُ به، أو ولدٍ صالحٍ يدعو له', arSrc: 'رواه مسلم', en: 'When a person dies, his deeds end except three: ongoing charity, beneficial knowledge, or a righteous child who prays for him.', enSrc: 'Muslim' },
  { ar: 'الحياءُ لا يأتي إلا بخيرٍ', arSrc: 'متفق عليه', en: 'Modesty brings nothing but good.', enSrc: 'Bukhari & Muslim' },
  { ar: 'مَن غشَّنا فليسَ مِنَّا', arSrc: 'رواه مسلم', en: 'Whoever deceives us is not one of us.', enSrc: 'Muslim' },
  { ar: 'المؤمنُ القويُّ خيرٌ وأحبُّ إلى اللهِ من المؤمنِ الضعيفِ، وفي كلٍّ خيرٌ', arSrc: 'رواه مسلم', en: 'The strong believer is better and more beloved to Allah than the weak believer, though in both there is good.', enSrc: 'Muslim' },
  { ar: 'المسلمُ أخو المسلمِ، لا يَظلِمُه ولا يُسلِمُه', arSrc: 'متفق عليه', en: 'A Muslim is the brother of a Muslim; he neither wrongs him nor forsakes him.', enSrc: 'Bukhari & Muslim' },
  { ar: 'الصلواتُ الخمسُ، والجمعةُ إلى الجمعةِ، ورمضانُ إلى رمضانَ، مُكفِّراتٌ لما بينهنَّ إذا اجتُنِبَتِ الكبائرُ', arSrc: 'رواه مسلم', en: 'The five daily prayers, Friday to Friday, and Ramadan to Ramadan are expiation for what is between them, so long as major sins are avoided.', enSrc: 'Muslim' },
  { ar: 'مَن صامَ رمضانَ إيمانًا واحتسابًا غُفِرَ له ما تقدَّمَ من ذنبِه', arSrc: 'متفق عليه', en: 'Whoever fasts Ramadan out of faith and seeking reward, his past sins are forgiven.', enSrc: 'Bukhari & Muslim' },
  { ar: 'مَن قامَ ليلةَ القدرِ إيمانًا واحتسابًا غُفِرَ له ما تقدَّمَ من ذنبِه', arSrc: 'متفق عليه', en: 'Whoever stands in prayer on the Night of Decree out of faith and seeking reward, his past sins are forgiven.', enSrc: 'Bukhari & Muslim' },
  { ar: 'الصيامُ جُنّةٌ', arSrc: 'متفق عليه', en: 'Fasting is a shield.', enSrc: 'Bukhari & Muslim' },
  { ar: 'إنَّ في الجسدِ مُضغةً، إذا صلَحَتْ صلَحَ الجسدُ كلُّه، وإذا فسَدَتْ فسَدَ الجسدُ كلُّه، ألا وهي القلبُ', arSrc: 'متفق عليه', en: 'In the body there is a piece of flesh; if it is sound the whole body is sound, and if it is corrupt the whole body is corrupt. Indeed, it is the heart.', enSrc: 'Bukhari & Muslim' },
  { ar: 'مَن بنى للهِ مسجدًا بنى اللهُ له مثلَه في الجنةِ', arSrc: 'متفق عليه', en: 'Whoever builds a mosque for Allah, Allah will build for him the like of it in Paradise.', enSrc: 'Bukhari & Muslim' },
  { ar: 'صلاةُ الجماعةِ تفضُلُ صلاةَ الفذِّ بسبعٍ وعشرينَ درجةً', arSrc: 'متفق عليه', en: 'Prayer in congregation is twenty-seven degrees better than praying alone.', enSrc: 'Bukhari & Muslim' },
  { ar: 'أحبُّ البلادِ إلى اللهِ مساجدُها', arSrc: 'رواه مسلم', en: 'The most beloved places to Allah are the mosques.', enSrc: 'Muslim' },
  { ar: 'إنَّ اللهَ جميلٌ يُحبُّ الجمالَ', arSrc: 'رواه مسلم', en: 'Allah is beautiful and loves beauty.', enSrc: 'Muslim' },
  { ar: 'مَن دلَّ على خيرٍ فله مثلُ أجرِ فاعلِه', arSrc: 'رواه مسلم', en: 'Whoever guides someone to good will have a reward like that of the one who does it.', enSrc: 'Muslim' },
  { ar: 'كلُّ معروفٍ صدقةٌ', arSrc: 'متفق عليه', en: 'Every act of kindness is a charity.', enSrc: 'Bukhari & Muslim' },
  { ar: 'اتقوا النارَ ولو بشِقِّ تمرةٍ', arSrc: 'متفق عليه', en: 'Guard yourselves against the Fire, even with half a date given in charity.', enSrc: 'Bukhari & Muslim' },
  { ar: 'لا تَحقِرَنَّ من المعروفِ شيئًا، ولو أن تلقى أخاكَ بوجهٍ طلقٍ', arSrc: 'رواه مسلم', en: 'Do not belittle any act of kindness, even meeting your brother with a cheerful face.', enSrc: 'Muslim' },
  { ar: 'مَن قالَ سبحانَ اللهِ وبحمدِه في يومٍ مئةَ مرةٍ، حُطَّتْ خطاياه وإن كانتْ مثلَ زبدِ البحرِ', arSrc: 'متفق عليه', en: 'Whoever says Subhan Allah wa bihamdihi a hundred times a day, his sins are wiped away even if they were like the foam of the sea.', enSrc: 'Bukhari & Muslim' },
  { ar: 'كلمتانِ خفيفتانِ على اللسانِ، ثقيلتانِ في الميزانِ، حبيبتانِ إلى الرحمنِ: سبحانَ اللهِ وبحمدِه، سبحانَ اللهِ العظيمِ', arSrc: 'متفق عليه', en: 'Two words light on the tongue, heavy on the scale, beloved to the Most Merciful: Subhan Allah wa bihamdihi, Subhan Allah al-Azim.', enSrc: 'Bukhari & Muslim' },
  { ar: 'مَن توضأَ فأحسنَ الوضوءَ خرجَتْ خطاياه من جسدِه حتى تخرجَ من تحتِ أظفارِه', arSrc: 'رواه مسلم', en: 'Whoever performs ablution well, his sins leave his body, even from under his nails.', enSrc: 'Muslim' },
  { ar: 'مَن صلَّى عليَّ صلاةً صلَّى اللهُ عليه بها عشرًا', arSrc: 'رواه مسلم', en: 'Whoever sends one blessing upon me, Allah sends ten blessings upon him.', enSrc: 'Muslim' },
  { ar: 'البيِّعانِ بالخيارِ ما لم يَتفرَّقا', arSrc: 'متفق عليه', en: 'The two parties to a transaction have the option to annul it so long as they have not parted.', enSrc: 'Bukhari & Muslim' },
  { ar: 'إنَّ اللهَ طيِّبٌ لا يقبلُ إلا طيِّبًا', arSrc: 'رواه مسلم', en: 'Allah is Pure and accepts only what is pure.', enSrc: 'Muslim' },
  { ar: 'البِرُّ حُسنُ الخُلُقِ', arSrc: 'رواه مسلم', en: 'Righteousness is good character.', enSrc: 'Muslim' },
  { ar: 'ليسَ الشديدُ بالصُّرَعةِ، إنما الشديدُ الذي يملِكُ نفسَه عند الغضبِ', arSrc: 'متفق عليه', en: 'The strong person is not the good wrestler; the strong is the one who controls himself when angry.', enSrc: 'Bukhari & Muslim' },
  { ar: 'لا يُلدغُ المؤمنُ من جُحرٍ واحدٍ مرتينِ', arSrc: 'متفق عليه', en: 'A believer is not bitten from the same hole twice.', enSrc: 'Bukhari & Muslim' },
  { ar: 'مَثَلُ المؤمنينَ في تَوادِّهم وتراحمِهم وتعاطفِهم مثلُ الجسدِ، إذا اشتكى منه عضوٌ تداعى له سائرُ الجسدِ بالسهرِ والحُمَّى', arSrc: 'متفق عليه', en: 'The believers in their mutual love, mercy, and compassion are like one body; when one limb suffers, the whole body responds with wakefulness and fever.', enSrc: 'Bukhari & Muslim' },
  { ar: 'إنَّ أحبَّ الكلامِ إلى اللهِ أربعٌ: سبحانَ اللهِ، والحمدُ للهِ، ولا إلهَ إلا اللهُ، واللهُ أكبرُ', arSrc: 'رواه مسلم', en: 'The most beloved words to Allah are four: Subhan Allah, al-hamdu lillah, la ilaha illa Allah, and Allahu akbar.', enSrc: 'Muslim' },
  { ar: 'مَن أحبَّ لقاءَ اللهِ أحبَّ اللهُ لقاءَه', arSrc: 'متفق عليه', en: 'Whoever loves to meet Allah, Allah loves to meet him.', enSrc: 'Bukhari & Muslim' },
  { ar: 'إنَّ اللهَ لا ينظرُ إلى صورِكم وأموالِكم، ولكن ينظرُ إلى قلوبِكم وأعمالِكم', arSrc: 'رواه مسلم', en: 'Allah does not look at your appearances or your wealth, but He looks at your hearts and your deeds.', enSrc: 'Muslim' },
  { ar: 'الدُّنيا متاعٌ، وخيرُ متاعِ الدنيا المرأةُ الصالحةُ', arSrc: 'رواه مسلم', en: 'This world is provision, and the best provision of this world is a righteous spouse.', enSrc: 'Muslim' },
  { ar: 'نِعمتانِ مغبونٌ فيهما كثيرٌ من الناسِ: الصحةُ والفراغُ', arSrc: 'رواه البخاري', en: 'There are two blessings which many people lose: health and free time.', enSrc: 'Bukhari' },
  { ar: 'احرِصْ على ما ينفعُك، واستعِنْ باللهِ ولا تعجِزْ', arSrc: 'رواه مسلم', en: 'Be keen on what benefits you, seek help from Allah, and do not give up.', enSrc: 'Muslim' },
  { ar: 'المرءُ مع مَن أحبَّ', arSrc: 'متفق عليه', en: 'A person will be with those he loves.', enSrc: 'Bukhari & Muslim' },
  { ar: 'مَن يُرِدِ اللهُ به خيرًا يُفقِّهْه في الدينِ', arSrc: 'متفق عليه', en: 'Whoever Allah wishes good for, He grants him understanding of the religion.', enSrc: 'Bukhari & Muslim' },
  { ar: 'إنَّ الرفقَ لا يكونُ في شيءٍ إلا زانَه، ولا يُنزَعُ من شيءٍ إلا شانَه', arSrc: 'رواه مسلم', en: 'Gentleness is not found in anything except that it beautifies it, and is not removed from anything except that it disgraces it.', enSrc: 'Muslim' },
  { ar: 'خِياركم أحاسنُكم أخلاقًا', arSrc: 'متفق عليه', en: 'The best of you are those with the best character.', enSrc: 'Bukhari & Muslim' },
  { ar: 'مَطْلُ الغنيِّ ظُلمٌ', arSrc: 'متفق عليه', en: 'The procrastination of a wealthy person in repaying a debt is injustice.', enSrc: 'Bukhari & Muslim' },
  { ar: 'اليدُ العليا خيرٌ من اليدِ السفلى', arSrc: 'متفق عليه', en: 'The upper hand is better than the lower hand; giving is better than receiving.', enSrc: 'Bukhari & Muslim' },
  { ar: 'ما نقصَتْ صدقةٌ من مالٍ', arSrc: 'رواه مسلم', en: 'Charity does not decrease wealth.', enSrc: 'Muslim' },
  { ar: 'سِبابُ المسلمِ فُسوقٌ، وقتالُه كفرٌ', arSrc: 'متفق عليه', en: 'Reviling a Muslim is sinful, and fighting him is disbelief.', enSrc: 'Bukhari & Muslim' },
  { ar: 'إنَّ اللهَ يُحبُّ العبدَ التقيَّ الغنيَّ الخفيَّ', arSrc: 'رواه مسلم', en: 'Allah loves the servant who is pious, content, and unnoticed.', enSrc: 'Muslim' },
  { ar: 'ما من مسلمٍ يغرِسُ غرسًا أو يزرعُ زرعًا، فيأكلُ منه طيرٌ أو إنسانٌ أو بهيمةٌ، إلا كان له به صدقةٌ', arSrc: 'متفق عليه', en: 'No Muslim plants a tree or sows a crop from which a bird, person, or animal eats, except that it is a charity for him.', enSrc: 'Bukhari & Muslim' },
  { ar: 'مَن صلَّى البردينِ دخلَ الجنةَ', arSrc: 'متفق عليه', en: 'Whoever prays the two cool prayers, Fajr and Asr, will enter Paradise.', enSrc: 'Bukhari & Muslim' },
];

export function hadithOfDay(d: Date): Hadith {
  const start = Date.UTC(d.getUTCFullYear(), 0, 0);
  const day = Math.floor((Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()) - start) / 86400000);
  return HADITHS[((day % HADITHS.length) + HADITHS.length) % HADITHS.length];
}
